- name: Login to Github repository locally
  local_action:
    module: docker_login
    registry: "{{ github_registry_url }}"
    username: "{{ github_deploy_user }}"
    password: "{{ github_deploy_token }}"

- name: Build frontend Docker image. Uses random numbers to force Docker to build certain parts of image every time
  local_action:
    module: docker_image
    source: build
    build:
      args:
        CUSTOM_UID: "{{ system_user_id_allu }}"
        CUSTOM_GID: "{{ system_group_id_allu }}"
        CACHEBUST: "{{ 9999999 |random }}"
      path: "{{ role_path }}/files/frontend_docker"
    name: "allu_frontend:{{ branch }}"
    force_source: true

- name: Push built allu_frontend Docker image to Github repository
  local_action:
    module: docker_image
    push: true
    source: local
    force_tag: true  # As branch may already be present, we need to enable overwriting of existing tags
    name: "allu_frontend:{{ branch }}"
    repository: "{{ github_registry_url }}/city-of-helsinki/allu/allu_frontend:{{ branch }}"
