- name: Build database Docker image. Uses random numbers to force Docker to build certain parts of image every time
  local_action:
    module: docker_image
    source: build
    build:
      args:
        CACHEBUST: "{{ 9999999 |random }}"
      path: "{{ role_path }}/files/database_docker"
    name: allu_database
    force_absent: true
    force_source: true


- name: remove existing docker image to avoid Ansible task caching
  local_action: file path=/tmp/allu_database.tar state=absent

- name: remove existing zipped docker image
  local_action: file path=/tmp/allu_database.tar.gz state=absent

# This task requires docker to be installed on the local host. Also the user who's executing Ansible has to belong to docker group to be
# able to use docker without super user rights
- name: save local Docker image as file on local host
  local_action: docker_image
                source=local
                name=allu_database
                archive_path=/tmp/allu_database.tar
                state=present

- name: gzip Docker image on local host
  local_action: command pigz /tmp/allu_database.tar

- name: copy Docker image to target host
  copy: src=/tmp/allu_database.tar.gz dest=/tmp
            owner=allu
            group=allu
            mode="u=rwx,g=rx,o=rx"

- name: extract tar from Docker gzipped image
  command: gunzip -f /tmp/allu_database.tar.gz

- name: start Docker services on remote host
  service: name=docker state=started
  become: yes

- name: stop and remove existing container from Docker
  docker_container:
    name: allu_database_container
    state: absent
  become: yes

- name: remove existing image from Docker
  docker_image:
    name=allu_database
    state=absent
    force_absent=true
    force_source=true
  become: yes

- name: add container to Docker
  docker_image:
    source=load
    name=allu_database
    state=present
    load_path=/tmp/allu_database.tar
  become: yes

- name: start container
  docker_container:
    name: allu_database_container
    image: allu_database
    shm_size: "{{ container_shm_size }}"
    restart_policy: always
    env:
      POSTGRES_PASSWORD: "{{ database_password_postgres }}"
    volumes:
      - /srv/data/allu/database/data:/var/lib/postgresql/data:rw
    published_ports:
      - "5432:5432"
  become: yes

- name: remove Docker image tar file
  file: path=/tmp/allu_database.tar state=absent

- name: wait for Postgresql to initialize
  postgresql_ping:
    login_host: localhost
    port: 5432
    login_user: postgres
    login_password: "{{ database_password_postgres }}"
  register: result
  until: result.is_available
  retries: 30
  delay: 4