- name: install PostgreSQL Python module needed by Ansible postgresql_user module
  apt:
    name:
      -  libpq-dev
      - python3-dev
    state: present
  become: yes

- name: Install psycopg2 with pip
  pip: name=psycopg2

- name: install support for psql command
  apt: name=postgresql-client-9.5 state=present
  become: yes

- name: allow postgresql connections from local network
  ufw: rule=allow src=10.0.0.0/8 port=5432
  become: yes
