- name: Login to GitLab repository locally
  local_action:
    module: docker_login
    registry: "{{ gitlab_registry_url }}"
    username: "{{ gitlab_deploy_user }}"
    password: "{{ gitlab_deploy_token }}"

- name: Build database Docker image. Uses random numbers to force Docker to build certain parts of image every time
  local_action:
    module: docker_image
    source: build
    build:
      args:
        CACHEBUST: "{{ 9999999 |random }}"
      path: "{{ role_path }}/files/database_docker"
    name: "allu_database:{{ branch }}"
    force_source: true

- name: Push built allu_database Docker image to GitLab repository
  local_action:
    module: docker_image
    push: true
    source: local
    force_tag: true  # As branch may already be present, we need to enable overwriting of existing tags
    name: "allu_database:{{ branch }}"
    repository: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_database:{{ branch }}"
