services:
  demo:
  tms:
    use_grid_names: true
    # origin for /tiles service
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: Working WMS url is http://localhost:8080/service?
    srs: ['EPSG:3879']

# known to work WMS request (just in case troubleshooting is required later on)
# http://10.176.127.67:8080/service?&SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=helsinki_kaupunkikartta&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=false&HEIGHT=256&WIDTH=256&SRS=EPSG%3A3879&BBOX=25505536,6666863.999998973,25509632,6670959.999998968


layers:
  - name: helsinki_kaupunkikartta
    title: Helsinki Kaupunkikartta
    sources: [hki_kaupunkikartta_cache]

caches:
  hki_kaupunkikartta_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_kaupunkikartta]
    cache:
      type: file

sources:
  hki_wms_kaupunkikartta:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: http://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/ows?
       layers: helsinki:Kaupunkikartta

grids:

  EPSG_3879:
    origin: nw
    srs: EPSG:3879
#    bbox: [24.4555930248625906, 59.9084989595170114, 25.2903558783246289, 60.4122137731072542]
#    bbox_srs: 'EPSG:4326'
    bbox: [25487000.0, 6644000.0, 25516000.0, 6690000.0]
    bbox_srs: 'EPSG:3879'

globals:
  cache:
    base_dir: /home/allu/mapproxy/cache_data
