services:
  demo:
  tms:
    use_grid_names: true
    # origin for /tiles service
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: Working WMS url is http://localhost:8080/service?
    srs: ['EPSG:3879']

layers:
  - name: helsinki_karttasarja
    title: Helsinki Karttasarja
    sources: [hki_karttasarja_cache]
  - name: helsinki_ortoilmakuva
    title: Helsinki Ortoilmakuva
    sources: [hki_ortoilmakuva_cache]
  - name: helsinki_kiinteistokartta
    title: Helsinki Kiinteistokartta
    sources: [hki_kiinteistokartta_cache]
  - name: helsinki_ajantasaasemakaava
    title: Helsinki Ajantatasa-asemakaava
    sources: [hki_ajantasaasemakaava_cache]
  - name: helsinki_opaskartta
    title: Helsinki Opaskartta
    sources: [hki_opaskartta_cache]
  - name: helsinki_kaupunginosajako
    title: Helsinki Kaupunginosajako
    sources: [hki_kaupunginosajako_cache]

caches:
####################################################################################
# NOTE! Whenever you're adding new caches, remember to add cleanups to seed.yaml !!!
####################################################################################
  hki_karttasarja_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_karttasarja]
    cache:
      type: file

  hki_ortoilmakuva_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_ortoilmakuva]
    cache:
      type: file

  hki_kiinteistokartta_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_kiinteistokartta]
    cache:
      type: file

  hki_ajantasaasemakaava_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_ajantasaasemakaava]
    cache:
      type: file

  hki_opaskartta_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_opaskartta]
    cache:
      type: file

  hki_kaupunginosajako_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_kaupunginosajako]
    cache:
      type: file

sources:
  hki_wms_karttasarja:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: http://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/ows?
       layers: helsinki:Karttasarja

  hki_wms_ortoilmakuva:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: http://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/ows?
       layers: helsinki:Ortoilmakuva_2015

  hki_wms_kiinteistokartta:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: http://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/ows?
       layers: helsinki:Kiinteistokartta

  hki_wms_ajantasaasemakaava:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: http://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/ows?
       layers: helsinki:Ajantasa-asemakaava

  hki_wms_opaskartta:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: http://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/ows?
       layers: helsinki:Opaskartta_Helsinki

  hki_wms_kaupunginosajako:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: http://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/ows?
       layers: helsinki:Kaupunginosajako


grids:
  EPSG_3879:
    origin: nw
    srs: EPSG:3879
#    bbox: [24.4555930248625906, 59.9084989595170114, 25.2903558783246289, 60.4122137731072542]
#    bbox_srs: 'EPSG:4326'
    bbox: [25487000.0, 6644000.0, 25516000.0, 6690000.0]
    bbox_srs: 'EPSG:3879'

globals:
  cache:
    base_dir: /home/allu/mapproxy/cache_data
