# add environment specific frontend variables here
http_port: 80
https_port: 443
proxy_domain: localhost:3000
proxypass_api_context: /api/
proxypass_api_target: http://localhost:9000/
proxypass_external_context: /external/
proxypass_external_target: http://localhost:9040/
proxypass_supervision_context: /supervision-api/
proxypass_supervision_target: http://localhost:9050/
server_admin: alluprojekti@gmail.com
ssl_certificate_file: apache-selfsigned.crt
ssl_certificate_key_file: apache-selfsigned.key
mapproxy_block_by_referer: false
