- name: install uncomplicated firewall (UFW) using Ubuntu repository
  apt: name=ufw state=present

- name: replace ufw after rules to block docker opening ports to outside world
  copy: src=after.rules
    dest=/etc/ufw
    owner=root
    group=root
    mode="u=rw"
    force=yes # because we're replacing, we need to force copying over existing file

- name: enable UFW
  ufw: state=enabled policy=deny

- name: allow SSH connections
  ufw: rule=allow port=22

- name: allow dcf monitoring connections
  ufw: rule=allow proto=udp port=161:162 src={{ item }}
  when: "'production' in group_names"
  with_items:
    - 10.42.21.37
    - 10.42.21.38
    - 10.42.21.39
    - 10.42.21.40
