- name: Install aptitude and update server
  apt:
    name: aptitude
    state: latest
    update_cache: yes
  become: yes

- include: hosts.yml

- include: firewall.yml

- name: add Finnish locale to system
  locale_gen: name=fi_FI.UTF-8 state=present

- include: usersetup.yml

- include: sshsetup.yml

- include: apt_install.yml

- include: configure_systemd.yml
