- name: Install aptitude and update server
  apt:
    name: aptitude
    state: latest
    update_cache: yes
  become: yes

- include_tasks: hosts.yml

- include_tasks: firewall.yml

- name: add Finnish locale to system
  locale_gen: name=fi_FI.UTF-8 state=present

- include_tasks: apt_install.yml

- include_tasks: configure_systemd.yml

- include_tasks: usersetup.yml

- include_tasks: sshsetup.yml
