# Add users and user configuration needed for deployment of everything else in this file

- name: create allu group to system
  group: name=allu state=present

- name: add allu user to system
  user: name=allu uid=1000 group=allu groups=adm,sudo
        password=$6$n4SJeU9XE$yI.E52oKLnzfYlbNKUSLpV8m.NI9UYD71x.3lWrpA0Rl8Jv8SOCOqXI77iQWCsc6xgUFbnIvHYusN/GYvIqfg0
        shell=/bin/bash
