# Add users and user configuration needed for deployment of everything else in this file

- name: create allu group to system
  group: name=allu state=present

- name: add allu user to system
  user: name=allu uid=1000 group=allu groups=adm,sudo
        password={{ system_password_allu }}
        shell=/bin/bash

- name: allow all sudo users to sudo without password
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL:ALL) NOPASSWD: ALL'"
