package fi.hel.allu.common.types;

public enum ApplicationNotificationType {
  STATUS_CHANGED,
  CONTENT_CHANGED,
  COMMENT_ADDED,
  ATTACHMENT_ADDED,
  SUPERVISION_ADDED,
  SUPERVISION_APPROVED,
  SUPERVISION_REJECTED,
  SUPERVISION_REMOVED,
  SUPERVISION_UPDATED,
  INVOICE_RECIPIENT_CHANGED,
  CUSTOMER_VALIDITY_PERIOD_CHANGED,
  EXTERNAL_CUSTOMER_VALIDITY_PERIOD_CHANGED,
  EXTERNAL_ATTACHMENT,
  EXTERNAL_OTHER_CHANGE
}
