- name: Login to Github repository locally
  local_action:
    module: docker_login
    registry: "{{ github_registry_url }}"
    username: "{{ github_deploy_user }}"
    password: "{{ github_deploy_token }}"

- name: Build allu_supervision_api Docker image
  local_action:
    module: docker_image
    source: build
    build:
      args:
        CUSTOM_UID: "{{ system_user_id_allu }}"
        CUSTOM_GID: "{{ system_group_id_allu }}"
        CACHEBUST: "{{ 9999999 |random }}"
        SERVICE_MEMORY: "{{ allu_service_memory_limit['supervision-api'] }}"
      path: "{{ role_path }}/files/supervision_api_docker"
    name: "allu_supervision_api:{{ branch }}"
    force_source: true

- name: Push built allu_supervision_api Docker image to Github repository
  local_action:
    module: docker_image
    push: true
    source: local
    force_tag: true  # As branch may already be present, we need to enable overwriting of existing tags
    name: "allu_supervision_api:{{ branch }}"
    repository: "{{ github_registry_url }}/city-of-helsinki/allu/allu_supervision_api:{{ branch }}"
