- name: Start Docker services on remote host
  service: name=docker state=started
  become: yes

- name: Stop and remove existing allu_sftpserver container from Docker
  docker_container:
    name: "{{ sftp_server_name }}"
    state: absent
  become: yes

- name: Remove existing allu_sftpserver image from Docker
  docker_image:
    name: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_sftpserver:{{ branch }}"
    state: absent
    force_absent: true
  become: yes
  when: "'test' in group_names or 'staging' in group_names"

- name: Login to GitLab repository at the remote
  docker_login:
    registry: "{{ gitlab_registry_url }}/vincit/allu/allu"
    username: "{{ gitlab_deploy_user }}"
    password: "{{ gitlab_deploy_token }}"
  become: yes
  when: "'dev' not in group_names"

- name: Pull allu_sftpserver Docker image from GitLab repository
  docker_image:
    source: pull
    name: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_sftpserver:{{ branch }}"
  become: yes
  when: "'dev' not in group_names"

- name: Start allu_sftpserver container
  docker_container:
    name: "{{ sftp_server_name }}"
    image: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_sftpserver:{{ branch }}"
    restart_policy: always
    volumes:
      - /home/allu/sftpserver/invoice:/home/allu/invoice
      - /home/allu/sftpserver/customer:/home/allu/customer
      - /home/allu/sftpserver/ssh:/etc/ssh/:rw
    ports:
      - "2222:22"
    networks:
      - name: "{{ network_name }}"
    command: "{{ sap_ftp_invoice_user }}:{{ sap_ftp_invoice_password }}:{{ system_user_id_allu}}:{{ system_group_id_allu }}:/customer/arch"
  become: yes
