version: '3.5'

services:
  allu-ui-service:
    build: ./allu-ui-service/
    image: allu_ui_service
    container_name: allu-ui-service
    ports:
      - "9000:9000"
  model-service:
    build: ./model-service/
    image: allu_model_service
    container_name: allu-model-service
    expose:
      - "9010"
    volumes:
      - /home/allu/model-service:/servicehome:rw
  search-service:
    build: ./search-service/
    image: allu_search_service
    container_name: allu-search-service
    expose:
      - "9020"
    volumes:
      - /home/allu/search-service:/servicehome:rw
  pdf-service:
    build: ./pdf-service/
    image: allu_pdf_service
    container_name: allu-pdf-service
    expose:
      - "9030"
    volumes:
      - /home/allu/pdf-service:/servicehome:rw
  allu-backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: allu_backend
    container_name: allu-backend
    ports:
      - "9040:9040"
      - "9050:9050"
    volumes:
      - /home/allu/allu-backend:/servicehome:rw

networks:
  default:
    name: allu-network
    external: true
