import {Pipe, PipeTransform} from '@angular/core';

const SOFT_HYPHEN = '\u00AD';

const HYPHENATED_DISTRICTS: Record<string, string> = {
  ALUEMERI: `ALUE${SOFT_HYPHEN}MERI`,
  KRUUNUNHAKA: `KRUUNUN${SOFT_HYPHEN}HAKA`,
  KLUUVI: 'KLUUVI',
  KAARTINKAUPUNKI: `KAARTIN${SOFT_HYPHEN}KAUPUNKI`,
  KAMPPI: 'KAMPPI',
  PUNAVUORI: `PUNA${SOFT_HYPHEN}VUORI`,
  EIRA: 'EIRA',
  ULLANLINNA: `ULLAN${SOFT_HYPHEN}LINNA`,
  KATAJANOKKA: `KATAJA${SOFT_HYPHEN}NOKKA`,
  KAIVOPUISTO: `KAIVO${SOFT_HYPHEN}PUISTO`,
  SÖRNÄINEN: `SÖRNÄINEN`,
  KALLIO: 'KALLIO',
  ALPPIHARJU: `ALPPI${SOFT_HYPHEN}HARJU`,
  'ETU-TÖÖLÖ': `ETU-TÖÖLÖ`,
  'TAKA-TÖÖLÖ': `TAKA-TÖÖLÖ`,
  MEILAHTI: `MEILAHTI`,
  RUSKEASUO: `RUSKEASUO`,
  PASILA: 'PASILA',
  LAAKSO: 'LAAKSO',
  'MUSTIKKAMAA-KORKEASAARI': `MUSTIKKA${SOFT_HYPHEN}MAA-KORKEA${SOFT_HYPHEN}SAARI`,
  LÄNSISATAMA: `LÄNSI${SOFT_HYPHEN}SATAMA`,
  HERMANNI: `HERMANNI`,
  VALLILA: `VALLILA`,
  TOUKOLA: `TOUKOLA`,
  KUMPULA: `KUMPULA`,
  KÄPYLÄ: `KÄPYLÄ`,
  KOSKELA: `KOSKELA`,
  VANHAKAUPUNKI: `VANHA${SOFT_HYPHEN}KAUPUNKI`,
  OULUNKYLÄ: `OULUN${SOFT_HYPHEN}KYLÄ`,
  HAAGA: 'HAAGA',
  MUNKKINIEMI: `MUNKKI${SOFT_HYPHEN}NIEMI`,
  LAUTTASAARI: `LAUTTA${SOFT_HYPHEN}SAARI`,
  KONALA: `KONALA`,
  KAARELA: `KAARELA`,
  PAKILA: `PAKILA`,
  TUOMARINKYLÄ: `TUOMARIN${SOFT_HYPHEN}KYLÄ`,
  VIIKKI: 'VIIKKI',
  PUKINMÄKI: `PUKIN${SOFT_HYPHEN}MÄKI`,
  MALMI: 'MALMI',
  TAPANINKYLÄ: `TAPANIN${SOFT_HYPHEN}KYLÄ`,
  SUUTARILA: `SUUTARILA`,
  SUURMETSÄ: `SUUR${SOFT_HYPHEN}METSÄ`,
  KULOSAARI: `KULO${SOFT_HYPHEN}SAARI`,
  HERTTONIEMI: `HERTTO${SOFT_HYPHEN}NIEMI`,
  TAMMISALO: `TAMMI${SOFT_HYPHEN}SALO`,
  VARTIOKYLÄ: `VARTIO${SOFT_HYPHEN}KYLÄ`,
  PITÄJÄNMÄKI: `PITÄJÄN${SOFT_HYPHEN}MÄKI`,
  MELLUNKYLÄ: `MELLUN${SOFT_HYPHEN}KYLÄ`,
  VARTIOSAARI: `VARTIO${SOFT_HYPHEN}SAARI`,
  LAAJASALO: `LAAJA${SOFT_HYPHEN}SALO`,
  VILLINKI: `VILLINKI`,
  SANTAHAMINA: `SANTA${SOFT_HYPHEN}HAMINA`,
  SUOMENLINNA: `SUOMEN${SOFT_HYPHEN}LINNA`,
  ULKOSAARET: `ULKO${SOFT_HYPHEN}SAARET`,
  VUOSAARI: `VUOSAARI`,
  ÖSTERSUNDOM: `ÖS${SOFT_HYPHEN}TER${SOFT_HYPHEN}SUN${SOFT_HYPHEN}DOM`,
  SALMENKALLIO: `SALMEN${SOFT_HYPHEN}KALLIO`,
  TALOSAARI: `TALO${SOFT_HYPHEN}SAARI`,
  KARHUSAARI: `KARHU${SOFT_HYPHEN}SAARI`,
  ULTUNA: 'ULTUNA'
};

@Pipe({name: 'hyphenateDistrict'})
export class HyphenateDistrictPipe implements PipeTransform {
  transform(value: string | null | undefined): string {
    if (!value) {
      return '';
    }

    const districtName = value.trim();
    const match = districtName.match(/^(\d+)\s+(.+)$/);
    const number = match?.[1];
    const name = match?.[2] ?? districtName;
    const hyphenatedName = HYPHENATED_DISTRICTS[name.toLocaleUpperCase('fi-FI')] ?? name;

    return number ? `${number} ${hyphenatedName}` : hyphenatedName;
  }
}
