- name: Login to Github repository locally
  local_action:
    module: docker_login
    registry: "{{ github_registry_url }}"
    username: "{{ github_deploy_user }}"
    password: "{{ github_deploy_token }}"

- name: Build allu_reporting_database Docker image. Uses random numbers to force Docker to build certain parts of image every time
  local_action:
    module: docker_image
    source: build
    build:
      args:
        CACHEBUST: "{{ 9999999 |random }}"
        POSTGRES_PWD: "{{ database_password_allu_reporting_postgres }}"
      path: "{{ role_path }}/files/reporting_database_docker"
    name: "allu_reporting_database:{{ branch }}"
    force_source: true

- name: Push built allu_reporting_database Docker image to Github repository
  local_action:
    module: docker_image
    push: true
    source: local
    force_tag: true  # As branch may already be present, we need to enable overwriting of existing tags
    name: "allu_reporting_database:{{ branch }}"
    repository: "{{ github_registry_url }}/city-of-helsinki/allu/allu_reporting_database:{{ branch }}"
