package fi.hel.allu.common.domain.types;

public enum InformationRequestFieldKey {
  CUSTOMER,
  INVOICING_CUSTOMER,
  PROPERTY_DEVELOPER,
  CONTRACTOR,
  REPRESENTATIVE,
  GEOMETRY,
  START_TIME,
  END_TIME,
  IDENTIFICATION_NUMBER,
  CLIENT_APPLICATION_KIND,
  APPLICATION_KIND,
  POSTAL_ADDRESS,
  WORK_DESCRIPTION,
  PROPERTY_IDENTIFICATION_NUMBER,
  ATTACHMENT,
  AREA,
  OTHER
}
