- name: Build ElasticSearch Docker image
  local_action:
    module: docker_image
    source: build
    build:
      args:
        CUSTOM_UID: "{{ system_user_id_allu }}"
        CUSTOM_GID: "{{ system_group_id_allu }}"
      path: "{{ role_path }}/files/elasticsearch_docker"
    name: allu_elasticsearch
    force_absent: true
    force_source: true


- name: remove existing docker image to avoid Ansible task caching
  local_action: file path=/tmp/allu_elasticsearch.tar state=absent

- name: remove existing zipped docker image
  local_action: file path=/tmp/allu_elasticsearch.tar.gz state=absent

# This task requires docker to be installed on the local host. Also the user who's executing Ansible has to belong to docker group to be
# able to use docker without super user rights
- name: save local Docker image as file on local host
  local_action: docker_image
                source=local
                name=allu_elasticsearch
                archive_path=/tmp/allu_elasticsearch.tar
                state=present

- name: gzip Docker image on local host
  local_action: command pigz /tmp/allu_elasticsearch.tar

- name: copy Docker image to target host
  copy: src=/tmp/allu_elasticsearch.tar.gz dest=/tmp
            owner=allu
            group=allu
            mode="u=rwx,g=rx,o=rx"

- name: extract tar from Docker gzipped image
  command: gunzip -f /tmp/allu_elasticsearch.tar.gz

- name: start Docker services on remote host
  service: name=docker state=started
  become: yes

- name: stop and remove existing container from Docker
  docker_container:
    name: "{{ elasticsearch_name }}"
    state: absent
  become: yes

- name: remove existing container from Docker
  docker_image:
    name=allu_elasticsearch
    state=absent
    force_absent=true
    force_source=true
  become: yes

- name: add container to Docker
  docker_image:
    source=load
    name=allu_elasticsearch
    state=present
    load_path=/tmp/allu_elasticsearch.tar
  become: yes

- name: Start Docker bridge network if not already running
  docker_network:
    name: "{{ network_name }}"
    driver: bridge
    appends: yes
  become: yes

- name: start container
  docker_container:
    name: "{{ elasticsearch_name }}"
    image: allu_elasticsearch
    restart_policy: always
    volumes:
      - /srv/data/allu/elasticsearch:/usr/share/elasticsearch/data:rw
    published_ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - name: "{{ network_name }}"
        aliases:
          - escontainer
    env:
      cluster.name: allu-cluster
      ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "false"
    ulimits:
      - "nofile:65536:65536"
      - "memlock:-1:-1"
  become: yes

- name: remove Docker image tar file
  file: path=/tmp/allu_elasticsearch.tar state=absent
