---


- set_fact: java_state="present"

- set_fact: java_state="latest"
  when: update_java == true

- name: Debian - Ensure Java is installed
  apt: name={{ java }} state={{java_state}} update_cache=yes force=yes
  when: ansible_os_family == 'Debian'