# runs preparation tasks against a fresh Ubuntu image
- name: prepare  Ubuntu for Allu deployment (done for all Ansible roles)
  hosts: all
  remote_user: "{{ deployment_user }}"
  become: yes
  gather_facts: no
  pre_tasks:
    - name: install python before other Ansible tasks, because Ansible modules depend on Python
      raw: apt -y install python3 python3-pip python-simplejson
    - name: update pip
      raw: python3 -m pip install --upgrade pip
    - name: gather facts for later use
      setup:
  roles:
    - imageprep
