# runs preparation tasks against a fresh Ubuntu 16.04 image
- name: prepare fresh Ubuntu 16.04 for Allu deployment (done for all Ansible roles)
  hosts: all
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2 before other Ansible tasks, because Ansible modules depend on Python
      raw: sudo apt-get -y install python-simplejson
  roles:
    - imageprep
