#Ansible role for elasticsearch that is used is based on https://github.com/elastic/ansible-elasticsearch

- name: install elasticsearch master nodes
  hosts: elasticsearch_master_nodes
  remote_user: allu
  become: yes
  roles:
      - { role: elasticsearch, es_instance_name: "allu-node",
      es_config: {
          node.name: "allu-node",
          cluster.name: "allu-cluster",
          http.port: 9200,
          transport.tcp.port: 9300,
          node.data: false,
          node.master: true,
          bootstrap.mlockall: true,
          network.host: 0.0.0.0,
          discovery.zen.ping.multicast.enabled: false}
      }
  vars:
        es_heap_size: 1g

# Commented data nodes out becouse we have only one server with limited resources in test environment
#- hosts: elasticsearch_data_nodes
#  remote_user: allu
#  become: yes
#  roles:
#    - { role: elasticsearch, es_instance_name: "allu-node",
#    es_config: {
#        node.name: "allu-node",
#        cluster.name: "allu-cluster",
#        http.port: 9200,
#        transport.tcp.port: 9300,
#        node.data: true,
#        node.master: false,
#        bootstrap.mlockall: false,
#        discovery.zen.ping.multicast.enabled: false,
#        discovery.zen.ping.unicast.hosts: "10.176.127.67:9300"}
#    }
#  vars:
#     es_heap_size: 1g
