- name: Install autossh
  apt: name=autossh state=present
  when: "'production' in group_names"
  become: yes

- name: Install daemon config for autossh
  template: src=autossh-service dest=/etc/systemd/system/autossh-sap-sftp-tunnel.service
  when: "'production' in group_names"
  become: yes

- name: Start autossh daemon
  service: name=autossh-sap-sftp-tunnel.service state=started daemon_reload=yes enabled=yes
  when: "'production' in group_names"
  become: yes
