
- name: Login to GitLab repository
  local_action:
    module: docker_login
    registry: "{{ gitlab_registry_url }}"
    username: "{{ gitlab_deploy_user }}" #ansible-deploy-token
    password: "{{ gitlab_deploy_token }}" #ansible-deploy-token

- name: Build backend Docker image. Uses random numbers to force Docker to build certain parts of image every time
  local_action:
    module: docker_image
    source: build
    build:
      args:
        CUSTOM_UID: "{{ system_user_id_allu }}"
        CUSTOM_GID: "{{ system_group_id_allu }}"
        CACHEBUST: "{{ 9999999 |random }}"
      path: "{{ role_path }}/files/backend_docker"
    name: "allu_backend:{{ branch }}"
    force_absent: true
    force_source: true

- name: Push built allu_backend Docker image to GitLab repository
  local_action:
    module: docker_image
    push: true
    source: local
    repository: "allu_backend:{{ branch }}"
    name: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_backend:{{ branch }}"

- name: start Docker services on remote host
  service: name=docker state=started
  become: yes

- name: stop and remove existing container from Docker
  docker_container:
    name: allu_backend
    state: absent
  become: yes

- name: remove existing image from Docker
  docker_image:
    name=allu_backend
    state=absent
    force_absent=true
    force_source=true
  become: yes
  when: "{{ branch }}  == 'master'"

- name: Pull allu_backend Docker image from GitLab repository
  local_action:
    module: docker_image
    source: pull
    repository: "allu_backend:{{ branch }}"
    name: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_backend:{{ branch }}"

- name: start container
  docker_container:
    name: allu_backend
    image: "allu_backend:{{ branch }}"
    restart_policy: always
    volumes:
      - /srv/data/allu:/servicehome:rw
    published_ports:
      - "9040:9040"
      - "9050:9050"
  become: yes
