
- name: Login to GitLab repository locally
  local_action:
    module: docker_login
    registry: "{{ gitlab_registry_url }}"
    username: "{{ gitlab_deploy_user }}"
    password: "{{ gitlab_deploy_token }}"
  when: "dev_var is undefined"

- name: Build backend Docker image. Uses random numbers to force Docker to build certain parts of image every time
  local_action:
    module: docker_image
    source: build
    build:
      args:
        CUSTOM_UID: "{{ system_user_id_allu }}"
        CUSTOM_GID: "{{ system_group_id_allu }}"
        CACHEBUST: "{{ 9999999 |random }}"
      path: "{{ role_path }}/files/backend_docker"
    name: "allu_backend:{{ branch }}"
    force_absent: true
    force_source: true

- name: tag allu_backend Docker image with repository. Run when developing locally.
  local_action:
    module: docker_image
    source: local
    name: "allu_ui_service:{{ branch }}"
    repository: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_ui_service:{{ branch }}"
  when: "dev_var is defined and dev_var"

- name: Push built allu_backend Docker image to GitLab repository
  local_action:
    module: docker_image
    push: true
    source: local
    force_tag: true  # As branch may already be present, we need to enable overwriting of existing tags
    name: "allu_backend:{{ branch }}"
    repository: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_backend:{{ branch }}"
  when: "dev_var is undefined"

- name: Start Docker services on remote host
  service: name=docker state=started
  become: yes

- name: Stop and remove existing allu_backend container from Docker
  docker_container:
    name: allu_backend
    state: absent
  become: yes

- name: Remove existing allu_backend image from Docker
  docker_image:
    name: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_backend:{{ branch }}"
    state: absent
    force_absent: true
    force_source: true
  become: yes
  when: "branch  == 'master' and dev_var is undefined"

- name: Login to GitLab repository at the remote
  docker_login:
    registry: "{{ gitlab_registry_url }}/vincit/allu/allu"
    username: "{{ gitlab_deploy_user }}"
    password: "{{ gitlab_deploy_token }}"
  become: yes
  when: "dev_var is undefined"

- name: Pull allu_backend Docker image from GitLab repository
  docker_image:
    source: pull
    name: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_backend:{{ branch }}"
  become: yes
  when: "dev_var is undefined"

- name: Start allu_backend container
  docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_backend:{{ branch }}"
    restart_policy: always
    volumes:
      - /home/allu:/servicehome:rw
    published_ports:
      - "9040:9040"
      - "9050:9050"
    networks:
      - name: "{{ network_name }}"
        aliases:
          - backendcontainer
  become: yes
