
- name: Build backend Docker image. Uses random numbers to force Docker to build certain parts of image every time
  local_action:
    module: docker_image
    source: build
    build:
      args:
        CUSTOM_UID: "{{ system_user_id_allu }}"
        CUSTOM_GID: "{{ system_group_id_allu }}"
        CACHEBUST: "{{ 9999999 |random }}"
      path: "{{ role_path }}/files/backend_docker"
    name: allu_backend
    force_absent: true
    force_source: true

- name: remove existing docker image to avoid Ansible task caching
  local_action: file path=/tmp/allu_backend.tar state=absent

- name: remove existing zipped docker image
  local_action: file path=/tmp/allu_backend.tar.gz state=absent

# This task requires docker to be installed on the local host. Also the user who's executing Ansible has to belong to docker group to be
# able to use docker without super user rights
- name: save local Docker image as file on local host
  local_action: docker_image
                source=local
                name=allu_backend
                archive_path=/tmp/allu_backend.tar
                state=present

- name: gzip Docker image on local host
  local_action: command pigz /tmp/allu_backend.tar

- name: copy Docker image to target host
  copy: src=/tmp/allu_backend.tar.gz dest=/tmp
            owner=allu
            group=allu
            mode="u=rwx,g=rx,o=rx"

- name: extract tar from Docker gzipped image
  command: gunzip -f /tmp/allu_backend.tar.gz

- name: start Docker services on remote host
  service: name=docker state=started
  become: yes

- name: stop and remove existing container from Docker
  docker_container:
    name: allu_backend
    state: absent
  become: yes

- name: remove existing container from Docker
  docker_image:
    name=allu_backend
    state=absent
    force_absent=true
    force_source=true
  become: yes

- name: add container to Docker
  docker_image:
    source=load
    name=allu_backend
    state=present
    load_path=/tmp/allu_backend.tar
  become: yes

- name: start container
  docker_container:
    name: allu_backend
    image: allu_backend
    restart_policy: always
    volumes:
      - /srv/data/allu:/servicehome:rw
    published_ports:
      - "9040:9040"
      - "9050:9050"
  become: yes

- name: remove Docker image tar file
  file: path=/tmp/allu_backend.tar state=absent
