
- name: copy Spring-Boot configuration files
  template: src={{ item }}.properties dest=/srv/data/allu/services/{{ item }}/{{ item }}.properties
            owner=allu
            group=allu
            mode="u=rwx,g=rx,o=rx"
  with_items: "{{ allu_service_list }}"

- name: copy logging configuration files
  template: src=included-logback.xml dest=/srv/data/allu/services/{{ item }}/included-logback.xml
            owner=allu
            group=allu
            mode="u=rwx,g=rx,o=rx"
  with_items: "{{ allu_service_list }}"

- name: add service runner scripts
  template: src=run_service.sh dest=/srv/data/allu/services/{{ item }}/run_{{ item }}.sh
            owner=allu
            group=allu
            mode="u=rwx,g=rx,o=rx"
  with_items: "{{ allu_service_list }}"

- name: copy autossh start script
  template: src=autossh-run.sh dest=/srv/data/allu/autossh-run.sh
            owner=allu
            group=allu
            mode="u=rwx,g=rx,o=rx"
