- name: allow local network access to backend processes
  ufw: rule=allow port={{ item }} src=10.0.0.0/8
  become: yes
  with_items:
    - 9000 # allu-ui-service
    - 9010 # model-service

- name: allow developer connections to test environment
  ufw: rule=allow port={{ item }} src=62.183.130.66
  when: "'test' in group_names"
  become: yes
  with_items:
      - 9000 # allu-ui-service
      - 9010 # model-service
