- include: firewall.yml
- include: cleanup.yml
- include: create_directories.yml
- include: copy_files.yml
- include: copy_stylesheets.yml
- include: allu_ui_service_docker.yml
- include: backend_docker.yml
