services:
  demo:
  tms:
    use_grid_names: true
    # origin for /tiles service
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: Working WMS url is http://localhost:8080/service?
    srs: ['EPSG:3879']

layers:
{% for layer in map_layers_common %}
  - name: {{ layer.name }}
    title: {{ layer.title }}
    sources: [{{layer.sources | join(", ")}}]
{% endfor %}
{% for layer in map_layers_restricted %}
  - name: {{ layer.name }}
    title: {{ layer.title }}
    sources: [{{layer.sources | join(", ")}}]
{% endfor %}

caches:
####################################################################################
# NOTE! Whenever you're adding new caches, remember to add cleanups to seed.yaml !!!
####################################################################################
  hki_karttasarja_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_karttasarja]
    cache:
      type: sqlite

  hki_kantakartta_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_kantakartta]
    cache:
      type: sqlite

  hki_ajantasa_asemakaava_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_ajantasa_asemakaava]
    cache:
      type: sqlite

  hki_kiinteistokartta_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_kiinteistokartta]
    cache:
      type: sqlite

  hki_ortoilmakuva_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_ortoilmakuva]
    cache:
      type: sqlite

#Data which requires authentication

  hki_maanomistus_vuokrausalueet_yhdistelma_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_maanomistus_vuokrausalueet_yhdistelma]
    cache:
      type: sqlite

  hki_maanomistus_vuokrausalueet_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_maanomistus_vuokrausalueet]
    cache:
      type: sqlite

  hki_maanomistus_sisainen_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_maanomistus_sisainen]
    cache:
      type: sqlite

  hki_maanalaiset_tilat_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_maanalaiset_tilat]
    cache:
      type: sqlite

  hki_maanalaiset_tilat_alueet_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_maanalaiset_tilat_alueet]
    cache:
      type: sqlite

  hki_maalampokaivot_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_maalampokaivot]
    cache:
      type: sqlite

  hki_porakaivo_vesi_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_porakaivo_vesi]
    cache:
      type: sqlite

  hki_johtokartta_sahko_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_johtokartta_sahko]
    cache:
      type: sqlite

  hki_johtokartta_tietoliikenne_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_johtokartta_tietoliikenne]
    cache:
      type: sqlite

  hki_johtokartta_kaukolampo_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_johtokartta_kaukolampo]
    cache:
      type: sqlite

  hki_johtokartta_kaukojaahdytys_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_johtokartta_kaukojaahdytys]
    cache:
      type: sqlite

  hki_johtokartta_kaasu_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_johtokartta_kaasu]
    cache:
      type: sqlite

  hki_johtokartta_vesijohto_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_johtokartta_vesijohto]
    cache:
      type: sqlite

  hki_johtokartta_viemari_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_johtokartta_viemari]
    cache:
      type: sqlite

  hki_johtokartta_imujatehuolto_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_imujatehuolto]
    cache:
      type: sqlite

  hki_johtokartta_yhdistelma_cache:
    grids: [EPSG_3879]
    sources: [hki_wms_johtokartta_yhdistelma]
    cache:
      type: sqlite

sources:

#Open data
  hki_wms_karttasarja:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://kartta.hel.fi/ws/geoserver/avoindata/wms
       layers: avoindata:Karttasarja

  hki_wms_kantakartta:
      type: wms
      supported_srs: ['EPSG:3879']
      req:
         url: https://kartta.hel.fi/ws/geoserver/avoindata/wms
         layers: avoindata:Kantakartta_harmaa

  hki_wms_ajantasa_asemakaava:
      type: wms
      supported_srs: ['EPSG:3879']
      req:
         url: https://kartta.hel.fi/ws/geoserver/avoindata/wms
         layers: avoindata:Ajantasa_asemakaava

  hki_wms_kiinteistokartta:
      type: wms
      supported_srs: ['EPSG:3879']
      req:
         url: https://kartta.hel.fi/ws/geoserver/avoindata/wms
         layers: avoindata:Kiinteistokartta

  hki_wms_ortoilmakuva:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://kartta.hel.fi/ws/geoserver/avoindata/wms
       layers: avoindata:Ortoilmakuva

#Data which requires authentication

#Maanomistus
  hki_wms_maanomistus_vuokrausalueet_yhdistelma:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Maanomistus_vuokrausalueet_yhdistelma
       transparent: true

  hki_wms_maanomistus_vuokrausalueet:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Maanomistus_vuokrausalueet
       transparent: true

  hki_wms_maanomistus_sisainen:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Maanomistus_sisainen
       transparent: true

#Maanalaiset tilat
  hki_wms_maanalaiset_tilat:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Maanalaiset_tilat
       transparent: true

  hki_wms_maanalaiset_tilat_alueet:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Maanalaiset_tilat_alueet
       transparent: true

#Kaivot
  hki_wms_maalampokaivot:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Maalampokaivot
       transparent: true

  hki_wms_porakaivo_vesi:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
      url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
      layers: helsinki:Porakaivo_vesi
      transparent: true

#Johtokartat
  hki_wms_johtokartta_sahko:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Johtokartta_sahko
       transparent: true

  hki_wms_johtokartta_tietoliikenne:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Johtokartta_tietoliikenne
       transparent: true

  hki_wms_johtokartta_kaukolampo:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Johtokartta_kaukolampo
       transparent: true

  hki_wms_johtokartta_kaukojaahdytys:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Johtokartta_kaukojaahdytys
       transparent: true

  hki_wms_johtokartta_kaasu:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Johtokartta_kaasu
       transparent: true

  hki_wms_johtokartta_vesijohto:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Johtokartta_vesijohto
       transparent: true

  hki_wms_johtokartta_viemari:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
       url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
       layers: helsinki:Johtokartta_viemari
       transparent: true

  hki_wms_imujatehuolto:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
      url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
      layers: helsinki:Johtokartta_imujatehuolto
      transparent: true

  hki_wms_johtokartta_yhdistelma:
    type: wms
    supported_srs: ['EPSG:3879']
    req:
      url: https://{{ geoserver_username }}:{{ geoserver_password }}@kartta.hel.fi/ws/geoserver/helsinki/wms
      layers: helsinki:Johtokartta_yhdistelma
      transparent: true

grids:
  EPSG_3879:
    origin: nw
    srs: EPSG:3879
    bbox: [25440000, 6630000, 25571072, 6761072]
    bbox_srs: 'EPSG:3879'
    tile_size: [256, 256]
    res: [
      128.0000000000, #  1      457142.85714286
      64.0000000000, #  2      228571.42857143
      32.0000000000, #  3      114285.71428571
      16.0000000000, #  4       57142.85714286
      8.0000000000, #  5       28571.42857143
      4.0000000000, #  6       14285.71428571
      2.0000000000, #  7        7142.85714286
      1.0000000000, #  8        3571.42857143
      0.5000000000, #  9        1785.71428571
      0.2500000000, # 10         892.85714286
      0.1250000000, # 11         446.42857143
      0.0625000000, # 12         223,214285715
      0.0312500000  # 13         111,607142858
    ]

globals:
  cache:
    base_dir: /home/allu/mapproxy/cache_data
  http:
    ssl_no_cert_checks: true
    access_control_allow_origin: ''
  image:
    resampling_method: bilinear
    paletted: true
    formats:
      image/png:
        mode: 'P'
        transparent: true
        encoding_options:
          quantizer: fastoctree