package fi.hel.allu.model.domain;

public enum ConfigurationKey {
  CUSTOMER_NOTIFICATION_RECEIVER_EMAIL,
  INVOICE_NOTIFICATION_RECEIVER_EMAIL,
  PLACEMENT_CONTRACT_DECISION_MAKER,
  WINTER_TIME_START,
  WINTER_TIME_END,
  PLACEMENT_CONTRACT_SECTION_NUMBER_YEAR
}
