package fi.hel.allu.model.domain;

public enum ConfigurationKey {
  CUSTOMER_NOTIFICATION_RECEIVER_EMAIL,
  INVOICE_NOTIFICATION_RECEIVER_EMAIL,
  EXCAVATION_ANNOUNCEMENT_DECISION_MAKER,
  AREA_RENTAL_DECISION_MAKER,
  TEMPORARY_TRAFFIC_ARRANGEMENTS_DECISION_MAKER,
  PLACEMENT_CONTRACT_DECISION_MAKER,
  EVENT_DECISION_MAKER,
  SHORT_TERM_RENTAL_DECISION_MAKER,
  WINTER_TIME_START,
  WINTER_TIME_END,
  PLACEMENT_CONTRACT_SECTION_NUMBER_YEAR
}
