package fi.hel.allu.model.domain;

import fi.hel.allu.common.types.ApplicationType;

/**
 * Placement contract (sijoitussopimus) specific data.
 */
public class PlacementContract extends ApplicationExtension {
  private Customer representative;
  private Contact contact;
  private String diaryNumber;
  private String additionalInfo;
  private String generalTerms;

  @Override
  public ApplicationType getApplicationType() {
    return ApplicationType.PLACEMENT_CONTRACT;
  }

  /**
   * In Finnish: Asiamies
   * @return the representative who takes care of the application.
   */
  public Customer getRepresentative() {
    return representative;
  }

  public void setRepresentative(Customer representative) {
    this.representative = representative;
  }

  /**
   * In Finnish: Yhteyshenkilö
   * @return the contact person of the application.
   */
  public Contact getContact() {
    return contact;
  }

  public void setContact(Contact contact) {
    this.contact = contact;
  }

  /**
   * In Finnish: Diaarinumero
   * @return the number generated by Ahjo system.
   */
  public String getDiaryNumber() {
    return diaryNumber;
  }

  public void setDiaryNumber(String diaryNumber) {
    this.diaryNumber = diaryNumber;
  }

  /**
   * In Finnish: lisätiedot.
   */
  public String getAdditionalInfo() {
    return additionalInfo;
  }

  public void setAdditionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  /**
   * In Finnish: Yleiset ehdot
   * @return General terms related to the application.
   */
  public String getGeneralTerms() {
    return generalTerms;
  }

  public void setGeneralTerms(String generalTerms) {
    this.generalTerms = generalTerms;
  }
}
