package fi.hel.allu.model.domain;

public enum PricingKey {
  // Excavation announcement
  HANDLING_FEE,
  HANDLING_FEE_SELF_SUPERVISION,
  SMALL_AREA_DAILY_FEE,
  MEDIUM_AREA_DAILY_FEE,
  LARGE_AREA_DAILY_FEE,

  // Short term rental
  BENJI_DAILY_PRICE,
  BRIDGE_BANNER_WEEKLY_PRICE_COMMERCIAL,
  BRIDGE_BANNER_WEEKLY_PRICE_NONCOMMERCIAL,
  CIRCUS_DAILY_PRICE,
  DOG_TRAINING_EVENT_ASSOCIATION_PRICE,
  DOG_TRAINING_EVENT_COMPANY_PRICE,
  DOG_TRAINING_FIELD_YEARLY_COMPANY,
  DOG_TRAINING_FIELD_YEARLY_ASSOCIATION,
  KESKUSKATU_SALES_TEN_SQM_PRICE,
  PROMOTION_OR_SALES_MONTHLY,
  SEASON_SALE_TEN_SQM_PRICE,
  STORAGE_AREA_MONTHLY_PRICE,
  SUMMER_THEATER_YEARLY_PRICE,
  URBAN_FARMING_TERM_PRICE,

  // Area rental
  SHORT_TERM_HANDLING_FEE,
  LONG_TERM_HANDLING_FEE,
  UNIT_PRICE,
  UNDERPASS_DICOUNT_PERCENTAGE,
  AREA_UNIT_M2
};
