package fi.hel.allu.model.domain;

import fi.hel.allu.common.domain.types.ApplicationKind;

public enum PricingKey {
  // Excavation announcement
  HANDLING_FEE,
  HANDLING_FEE_SELF_SUPERVISION,
  SMALL_AREA_DAILY_FEE,
  MEDIUM_AREA_DAILY_FEE,
  LARGE_AREA_DAILY_FEE,
  LESS_THAN_60M2,
  FROM_60_TO_120M2,
  FROM_121_TO_250M2,
  FROM_251_TO_500M2,
  FROM_501_TO_1000M2,
  MORE_THAN_1000M2,

  // Short term rental
  BENJI_DAILY_PRICE,
  BRIDGE_BANNER_WEEKLY_PRICE_COMMERCIAL,
  BRIDGE_BANNER_WEEKLY_PRICE_NONCOMMERCIAL,
  CIRCUS_DAILY_PRICE,
  DOG_TRAINING_EVENT_ASSOCIATION_PRICE,
  DOG_TRAINING_EVENT_COMPANY_PRICE,
  DOG_TRAINING_FIELD_YEARLY_COMPANY,
  DOG_TRAINING_FIELD_YEARLY_ASSOCIATION,
  KESKUSKATU_SALES_TEN_SQM_PRICE,
  PROMOTION_OR_SALES_MONTHLY,
  SEASON_SALE_TEN_SQM_PRICE,
  STORAGE_AREA_MONTHLY_PRICE,
  SUMMER_THEATER_YEARLY_PRICE,
  URBAN_FARMING_TERM_PRICE,
  SUMMER_TERRACE,
  WINTER_TERRACE,
  PARKLET,

  // Area rental
  MINOR_DISTURBANCE_HANDLING_FEE,
  MAJOR_DISTURBANCE_HANDLING_FEE,
  UNIT_PRICE,
  UNDERPASS_DICOUNT_PERCENTAGE,
  AREA_UNIT_M2,
  FROM_15M2;

  public static PricingKey forTerraceKind(ApplicationKind kind) {
    switch (kind) {
    case SUMMER_TERRACE:
      return PricingKey.SUMMER_TERRACE;
    case WINTER_TERRACE:
      return PricingKey.WINTER_TERRACE;
    case PARKLET:
      return PricingKey.PARKLET;
    default:
      return null;
    }
  }
}
