- name: Login to Github repository locally
  local_action:
    module: docker_login
    registry: "{{ github_registry_url }}"
    username: "{{ github_deploy_user }}"
    password: "{{ github_deploy_token }}"

- name: Build Test SFTP Server Docker image
  local_action:
    module: docker_image
    source: build
    build:
      path: "{{ role_path }}/files/sftpserver_docker"
    name: "allu_sftpserver:{{ branch }}"
    force_source: true

- name: Push built allu_sftpserver Docker image to Github repository
  local_action:
    module: docker_image
    push: true
    source: local
    force_tag: true  # As branch may already be present, we need to enable overwriting of existing tags
    name: "allu_sftpserver:{{ branch }}"
    repository: "{{ github_registry_url }}/city-of-helsinki/allu/allu_sftpserver:{{ branch }}"
