- name: Start Allu Docker network on db server
  hosts: dbservers
  remote_user: allu
  tasks:
    - name: Start Docker bridge network if not already running
      docker_network:
        name: "{{ network_name }}"
        driver: bridge
        ipam_config:
          - subnet: '172.18.0.0/16'
            gateway: 172.18.0.1
        force: yes
      become: yes
  become: no
