version: '3.5'

services:
  allu_database:
    build: ./
    image: allu_database
    container_name: allu-database
    volumes:
      - ./local_development_conf/dev-add-report.sql:/docker-entrypoint-initdb.d/dev-add-report.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      # <Port exposed> : < PostgreSQL Port running inside container>
      - "5432:5432"
  allu-node:
    build: ./elasticsearch/
    image: allu_elasticsearch
    container_name: allu-elasticsearch
    environment:
      node.name: allu-node
      cluster.name: allu-cluster
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
      - "9300:9300"

networks:
  default:
    name: allu-network
    driver: bridge
