version: '3.1'

services:
  allu_database:
    build: ./
    volumes:
      - ./dev-add-report.sql:/docker-entrypoint-initdb.d/dev-add-report.sql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "5432:5432"
  allu-node:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    container_name: allu-node
    environment:
      - node.name=allu-node
      - cluster.name=allu-cluster
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"


