version: '3.1'

services:
  allu_database:
    build: ./
    volumes:
      - ./dev-add-report.sql:/docker-entrypoint-initdb.d/dev-add-report.sql
    ports:
      # <Port exposed> : < PostgreSQL Port running inside container>
      - "5432:5432"
  allu-node:
    build: ./elasticsearch/
    container_name: allu-node
    environment:
      - node.name=allu-node
      - cluster.name=allu-cluster
    ports:
      - "9200:9200"
      - "9300:9300"


