
- name: copy Spring-Boot configuration files
  template: src=allu-etl.properties dest=/home/allu/services/etl/allu-etl.properties
            owner=allu
            group=allu
            mode="u=rwx,g=rx,o=rx"

- name: copy logging configuration files
  copy: src=etl/included-logback.xml
        dest=/home/allu/services/etl/included-logback.xml
        owner=allu
        group=allu
        mode="u=rwx,g=rx,o=rx"
