- name: Start Docker services on remote host
  service: name=docker state=started
  become: yes

- name: Stop and remove existing allu_etl container from Docker
  docker_container:
    name: "{{ etl_service_name }}"
    state: absent
  become: yes

- name: Remove existing allu_etl image from Docker
  docker_image:
    name: "{{ github_registry_url }}/city-of-helsinki/allu/allu_etl:{{ branch }}"
    state: absent
    force_absent: true
  become: yes
  when: "'test' in group_names or 'staging' in group_names"

- name: Login to Github repository at the remote
  docker_login:
    registry: "{{ github_registry_url }}/city-of-helsinki/allu"
    username: "{{ github_deploy_user }}"
    password: "{{ github_deploy_token }}"
  become: yes

- name: Pull allu_etl Docker image from Github repository
  docker_image:
    source: pull
    name: "{{ github_registry_url }}/city-of-helsinki/allu/allu_etl:{{ branch }}"
  become: yes

- name: Start allu_etl container
  docker_container:
    name: "{{ etl_service_name }}"
    image: "{{ github_registry_url }}/city-of-helsinki/allu/allu_etl:{{ branch }}"
    restart_policy: always
    volumes:
      - /home/allu:/servicehome:rw
    networks:
      - name: "{{ network_name }}"
  become: yes
