package fi.hel.allu.servicecore.domain;

import fi.hel.allu.common.domain.types.ApplicationType;

/**
 * Placement contract (sijoitussopimus) specific data.
 */
public class PlacementContractJson extends ApplicationExtensionJson {
  private String identificationNumber;
  private String propertyIdentificationNumber;
  private String additionalInfo;
  private String contractText;

  @Override
  public ApplicationType getApplicationType() {
    return ApplicationType.PLACEMENT_CONTRACT;
  }

  /**
   * In Finnish: asiointitunnus
   * @return the number generated by Ahjo system.
   */
  public String getIdentificationNumber() {
    return identificationNumber;
  }

  public void setIdentificationNumber(String identificationNumber) {
    this.identificationNumber = identificationNumber;
  }

  /**
   * In Finnish: kiinteistötunnus
   */
  public String getPropertyIdentificationNumber() {
    return propertyIdentificationNumber;
  }

  public void setPropertyIdentificationNumber(String propertyIdentificationNumber) {
    this.propertyIdentificationNumber = propertyIdentificationNumber;
  }

  /**
   * In Finnish: lisätiedot.
   */
  public String getAdditionalInfo() {
    return additionalInfo;
  }

  public void setAdditionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  /**
   * In Finnish: sopimusteksti
   * @return General terms related to the application.
   */
  public String getContractText() {
    return contractText;
  }

  public void setContractText(String contractText) {
    this.contractText = contractText;
  }
}
