# add environment specific backend variables here

# process specific Java -Xmx settings for limiting memory usage. If nothing is specified here for a service, service will use the default
# value specified elsewhere
allu_service_memory_limit:

database_host: 172.17.0.1

model_service_host: localhost
model_service_port: 9010

search_service_host: localhost
search_service_port: 9020

pdf_service_host: localhost
pdf_service_port: 9030

mail_server_host: securemail.vincit.cloud
mail_server_port: 25
mail_server_auth: false
email_allowed_addresses: "*@vincit.fi,*@hel.fi"
email_sender_address: Allu Staging Aluevaraus <noreply@staging.allu.kaupunkiymparisto.fi>

invoice_cronstring: "0 0 0 24 4 ?"
sap_ftp_invoice_host: 137.163.136.62
sap_ftp_invoice_port: 22
sap_ftp_invoice_directory: /

invoice_archivedir: /home/allu/scheduler-service/sap/invoice-archive

# Customer update SFTP configuration
sap_ftp_customer_host: 137.163.136.62
sap_ftp_customer_port: 22
sap_ftp_customer_directory: /
sap_ftp_customer_arch_directory: /arch

# Customer update configuration
customer_update_enabled: true
customer_update_cronstring: "0 0/30 * * * ?"
customer_update_sourcedir: /home/allu/scheduler-service/sap/customer-process
customer_archivedir: /home/allu/scheduler-service/sap/customer-archive
customer_failedupdatedir: /home/allu/scheduler-service/sap/customer-failed

customer_notification_cronstring: "0 0 7 * * *"
ui_baseurl: https://staging.allu.kaupunkiymparisto.fi
