runs_in_production: true

model_service_host: localhost
model_service_port: 9010

search_service_host: localhost
search_service_port: 9020

oauth2_redirect_uri: http://94.199.118.86/oauth2/

mail_server_host: smtp.gmail.com
mail_server_port: 587
