- name: Create cron job for staging database backup
  cron:
    name: Backup database
    hour: 16
    minute: 0
    user: root
    job: "echo \"Start backup: $(date)\" >> /etc/cron.d/allu_database-backup.log; cd /srv/backup/allu/database/dumps/; chmod 0600 db_backup-latest.tar.gz; rm db_backup-latest.tar.gz; pg_basebackup -h localhost -U postgres -D /srv/backup/allu/database/dumps/latest -X stream; tar --remove-files -zcf db_backup-latest.tar.gz latest/ && chmod 0400 db_backup-latest.tar.gz; echo \"End backup: $(date)\" >> /etc/cron.d/allu_database-backup.log;"
    cron_file: allu_database-backup
  when: "'staging' in group_names"
  become: yes
  become_user: root

- name: Create cron job for production database backup
  cron:
    name: Backup database
    hour: 21
    minute: 30
    user: root
    job: "echo \"Start backup: $(date)\" >> /etc/cron.d/allu_database-backup.log; cd /srv/backup/allu/database/dumps/; chmod 0600 db_backup-latest.tar.gz; rm db_backup-latest.tar.gz; pg_basebackup -h localhost -U postgres -D /srv/backup/allu/database/dumps/latest -X stream >> /etc/cron.d/allu_database-backup.log 2>&1; df -h >> /etc/cron.d/allu_database-backup.log; tar --remove-files -zcf db_backup-latest.tar.gz latest/ >> /etc/cron.d/allu_database-backup.log 2>&1 && chmod 0400 db_backup-latest.tar.gz; echo \"End backup: $(date)\" >> /etc/cron.d/allu_database-backup.log;"
    cron_file: allu_database-backup
  when: "'production' in group_names"
  become: yes
  become_user: root

- name: Create cron job for wal archive cleaning
  cron:
    name: Clean wal files
    hour: 5
    minute: 0
    user: root
    job: "/usr/local/bin/wal_cleanup.sh"
    cron_file: allu_archive-cleanup
  when: "'production' in group_names"
  become: yes
  become_user: root

- name: Create cron job for wal archival process checking
  cron:
    name: Check wal archiving
    minute: 45
    user: root
    job: "/usr/local/bin/wal_archiver_checker.sh"
    cron_file: allu_archiver-check
  when: "'production' in group_names"
  become: yes
  become_user: root
