- name: create data directory for SFTP Server
  file: path=/home/allu/sftpserver
        state=directory
        owner=allu
        group=allu
        mode="u=rwx,g=r,o=r"
  become: yes

- name: create target directory for SAP invoices
  file: path=/home/allu/sftpserver/invoice
        state=directory
        owner=allu
        group=allu
        mode="u=rwx,g=r,o=r"
  become: yes

- name: create source directory for SAP customers
  file: path=/home/allu/sftpserver/customer
        state=directory
        owner=allu
        group=allu
        mode="u=rwx,g=r,o=r"
  become: yes

- name: create archive directory for SAP customers
  file: path=/home/allu/sftpserver/customer/arch
        state=directory
        owner=allu
        group=allu
        mode="u=rwx,g=r,o=r"
  become: yes
