- name: Build Test SFTP Server Docker image
  local_action:
    module: docker_image
    source: build
    build:
      path: "{{ role_path }}/files/sftpserver_docker"
    name: allu_sftpserver
    force_absent: true
    force_source: true

- name: remove existing docker image to avoid Ansible task caching
  local_action: file path=/tmp/allu_sftpserver.tar state=absent

- name: remove existing zipped docker image
  local_action: file path=/tmp/allu_sftpserver.tar.gz state=absent

# This task requires docker to be installed on the local host. Also the user who's executing Ansible has to belong to docker group to be
# able to use docker without super user rights
- name: save local Docker image as file on local host
  local_action: docker_image
                source=local
                name=allu_sftpserver
                archive_path=/tmp/allu_sftpserver.tar
                state=present

- name: gzip Docker image on local host
  local_action: command pigz /tmp/allu_sftpserver.tar

- name: copy Docker image to target host
  copy: src=/tmp/allu_sftpserver.tar.gz dest=/tmp
            owner=allu
            group=allu
            mode="u=rwx,g=rx,o=rx"

- name: extract tar from Docker gzipped image
  command: gunzip -f /tmp/allu_sftpserver.tar.gz

- name: start Docker services on remote host
  service: name=docker state=started
  become: yes

- name: stop and remove existing container from Docker
  docker_container:
    name: allu_sftpserver_container
    state: absent
  become: yes

- name: remove existing container from Docker
  docker_image:
    name=allu_sftpserver
    state=absent
    force_absent=true
    force_source=true
  become: yes

- name: add container to Docker
  docker_image:
    source=load
    name=allu_sftpserver
    state=present
    load_path=/tmp/allu_sftpserver.tar
  become: yes

- name: Start Docker bridge network if not already running
  docker_network:
    name: allu_backend_bridge_network
    driver: bridge
    driver_options:
      com.docker.network.bridge.host_binding_ipv4: 172.18.0.1
    ipam_config:
      - subnet: '172.18.0.0/16'
        gateway: 172.18.0.1
    appends: yes
  become: yes

- name: start container
  docker_container:
    name: allu_sftpserver_container
    image: allu_sftpserver
    restart_policy: always
    volumes:
      - /home/allu/sftpserver/invoice:/home/allu/invoice
      - /home/allu/sftpserver/customer:/home/allu/customer
    ports:
      - "2222:22"
    networks:
      - name: allu_backend_bridge_network
    command: "{{ sap_ftp_invoice_user }}:{{ sap_ftp_invoice_password }}:{{ system_user_id_allu}}:{{ system_group_id_allu }}:/customer/arch"
  become: yes

- name: remove Docker image tar file
  file: path=/tmp/allu_sftpserver.tar state=absent
