- name: allow Docker container access to SFTP server in test environment
  ufw: rule=allow port=2222 src=172.18.0.1/24
  become: yes

- name: allow local network access to SFTP server in test environment
  ufw: rule=allow port=2222 src=10.0.0.0/8
  become: yes


