delete from allu.application_tag where type in (
  'OPERATIONAL_CONDITION_REJECTED',
  'OPERATIONAL_CONDITION_ACCEPTED',
  'FINAL_SUPERVISION_REQUESTED',
  'FINAL_SUPERVISION_REJECTED',
  'FINAL_SUPERVISION_ACCEPTED'
);
