-- DO NOT EDIT THIS FILE MANUALLY!

-- This file was autogenerated. The command used was:
-- java -Dloader.main=fi.hel.allu.model.deployment.LocationGeometryReader -classpath model-service-1.0-SNAPSHOT.jar org.springframework.boot.loader.PropertiesLauncher 2019-01-16_rautatientori.geojson sects.sql

-- See the documentation for more info.

CREATE FUNCTION check_allu_name(areaname TEXT, sectionname TEXT)
RETURNS VOID AS $$
DECLARE
   match_count INT;
BEGIN
   IF sectionname IS NULL OR sectionname = '' THEN
       SELECT COUNT(*) INTO STRICT match_count FROM
           (SELECT DISTINCT a.name as areaname, fl.section as section FROM
            allu.fixed_location as fl inner join allu.location_area as a on fl.area_id=a.id) as l WHERE
           l.areaname LIKE check_allu_name.areaname AND l.section IS NULL;
   ELSE
       SELECT COUNT(*) INTO STRICT match_count FROM
           (SELECT DISTINCT a.name as areaname, fl.section as section FROM
            allu.fixed_location as fl inner join allu.location_area as a on fl.area_id=a.id) as l WHERE
           l.areaname LIKE check_allu_name.areaname AND l.section = sectionname;
   END IF;
   IF match_count <> 1 THEN
       RAISE EXCEPTION 'Name % matches % areas in database', check_allu_name.areaname, match_count;
   END IF;
END;
$$ LANGUAGE plpgsql;
-- input file: 2019-01-16_rautatientori.geojson
select check_allu_name('Rautatientori%','A');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496871.89764982 6673109.106864716,25496870.15292356 6673142.882680183,25496891.667774785 6673144.3311953135,25496893.333689056 6673110.275018157,25496871.89764982 6673109.106864716)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Rautatientori%') and fixed_location.section = 'A';
select check_allu_name('Rautatientori%','D');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496889.24873552 6673187.058582979,25496914.291098855 6673188.424581739,25496916.556500614 6673145.642377382,25496891.667774785 6673144.3311953135,25496889.24873552 6673187.058582979)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Rautatientori%') and fixed_location.section = 'D';
select check_allu_name('Rautatientori%','E');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496866.655489534 6673210.589362897,25496867.770640835 6673189.001116278,25496877.47872566 6673189.550037191,25496876.397271853 6673211.058372941,25496866.655489534 6673210.589362897)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Rautatientori%') and fixed_location.section = 'E';
select check_allu_name('Rautatientori%','B');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496916.556500614 6673145.642377382,25496918.009936098 6673115.829461085,25496913.851365156 6673111.070257046,25496893.333689056 6673110.275018157,25496891.667774785 6673144.3311953135,25496916.556500614 6673145.642377382)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Rautatientori%') and fixed_location.section = 'B';
select check_allu_name('Rautatientori%','C');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496867.92813817 6673185.95212664,25496870.15292356 6673142.882680183,25496891.667774785 6673144.3311953135,25496889.24873552 6673187.058582979,25496867.92813817 6673185.95212664)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Rautatientori%') and fixed_location.section = 'C';
select check_allu_name('Rautatientori%','F');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496896.12639393 6673212.045112652,25496912.93424006 6673212.827576915,25496914.047865696 6673191.5605314085,25496897.407650612 6673190.635583466,25496896.12639393 6673212.045112652)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Rautatientori%') and fixed_location.section = 'F';
DROP FUNCTION check_allu_name(TEXT, TEXT);
