-- DO NOT EDIT THIS FILE MANUALLY!

-- This file was autogenerated. The command used was:
-- java -Dloader.main=fi.hel.allu.model.deployment.LocationGeometryReader -classpath ./model-service-1.0-SNAPSHOT.jar org.springframework.boot.loader.PropertiesLauncher keskuskadun_sesonkimyynti_palautus.geojson keskuskatu.sql

-- See the documentation for more info.

CREATE FUNCTION check_allu_name(areaname TEXT, sectionname TEXT)
RETURNS VOID AS $$
DECLARE
   match_count INT;
BEGIN
   IF sectionname IS NULL OR sectionname = '' THEN
       SELECT COUNT(*) INTO STRICT match_count FROM
           (SELECT DISTINCT a.name as areaname, fl.section as section FROM
            allu.fixed_location as fl inner join allu.location_area as a on fl.area_id=a.id) as l WHERE
           l.areaname LIKE check_allu_name.areaname AND l.section IS NULL;
   ELSE
       SELECT COUNT(*) INTO STRICT match_count FROM
           (SELECT DISTINCT a.name as areaname, fl.section as section FROM
            allu.fixed_location as fl inner join allu.location_area as a on fl.area_id=a.id) as l WHERE
           l.areaname LIKE check_allu_name.areaname AND l.section = sectionname;
   END IF;
   IF match_count <> 1 THEN
       RAISE EXCEPTION 'Name % matches % areas in database', check_allu_name.areaname, match_count;
   END IF;
END;
$$ LANGUAGE plpgsql;
-- input file: keskuskadun_sesonkimyynti_palautus.geojson
select check_allu_name('Keskuskatu%','F');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(MULTIPOLYGON(((25496833.488304466 6672978.048056512,25496830.329642925 6672977.8552211635,25496830.15978746 6672981.020974275,25496833.311317 6672981.206854144,25496833.488304466 6672978.048056512))))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Keskuskatu%') and fixed_location.section = 'F';
select check_allu_name('Keskuskatu%','A');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(MULTIPOLYGON(((25496829.985013157 6672984.187022485,25496826.826356716 6672983.994190153,25496826.65650457 6672987.159943455,25496829.808029022 6672987.345820311,25496829.985013157 6672984.187022485))))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Keskuskatu%') and fixed_location.section = 'A';
select check_allu_name('Keskuskatu%','D');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(MULTIPOLYGON(((25496833.31324998 6672981.214284828,25496830.154591154 6672981.021449628,25496829.98473599 6672984.187202763,25496833.136262827 6672984.37308248,25496833.31324998 6672981.214284828))))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Keskuskatu%') and fixed_location.section = 'D';
select check_allu_name('Keskuskatu%','E');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(MULTIPOLYGON(((25496830.333087597 6672977.864115684,25496827.17442573 6672977.671283051,25496827.004572976 6672980.83703631,25496830.156102844 6672981.022913467,25496830.333087597 6672977.864115684))))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Keskuskatu%') and fixed_location.section = 'E';
select check_allu_name('Keskuskatu%','B');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(MULTIPOLYGON(((25496833.143645447 6672984.382644147,25496829.984989345 6672984.189809093,25496829.81513448 6672987.355562248,25496832.9666586 6672987.5414418215,25496833.143645447 6672984.382644147))))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Keskuskatu%') and fixed_location.section = 'B';
select check_allu_name('Keskuskatu%','C');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(MULTIPOLYGON(((25496830.160281606 6672981.0261970535,25496827.001622453 6672980.833364573,25496826.83177 6672983.999117851,25496829.98329716 6672984.184994859,25496830.160281606 6672981.0261970535))))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Keskuskatu%') and fixed_location.section = 'C';
DROP FUNCTION check_allu_name(TEXT, TEXT);
