-- DO NOT EDIT THIS FILE MANUALLY!

-- This file was autogenerated. The command used was:
-- java -Dloader.main=fi.hel.allu.model.deployment.LocationGeometryReader -classpath /home/mikko/.m2/repository/fi/hel/allu/model-service/1.0-SNAPSHOT/model-service-1.0-SNAPSHOT.jar org.springframework.boot.loader.PropertiesLauncher tmp/2018-03-28_rautatientori.geojson test-geojson.sql

-- See the documentation for more info.

CREATE FUNCTION check_allu_name(areaname TEXT, sectionname TEXT)
RETURNS VOID AS $$
DECLARE
   match_count INT;
BEGIN
   IF sectionname IS NULL OR sectionname = '' THEN
       SELECT COUNT(*) INTO STRICT match_count FROM
           (SELECT DISTINCT a.name as areaname, fl.section as section FROM
            allu.fixed_location as fl inner join allu.location_area as a on fl.area_id=a.id) as l WHERE
           l.areaname LIKE check_allu_name.areaname AND l.section IS NULL;
   ELSE
       SELECT COUNT(*) INTO STRICT match_count FROM
           (SELECT DISTINCT a.name as areaname, fl.section as section FROM
            allu.fixed_location as fl inner join allu.location_area as a on fl.area_id=a.id) as l WHERE
           l.areaname LIKE check_allu_name.areaname AND l.section = sectionname;
   END IF;
   IF match_count <> 1 THEN
       RAISE EXCEPTION 'Name % matches % areas in database', check_allu_name.areaname, match_count;
   END IF;
END;
$$ LANGUAGE plpgsql;
-- input file: tmp/2018-03-28_rautatientori.geojson
select check_allu_name('Rautatientori%','A');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496869.323092405 6673148.11807978,25496892.34366284 6673149.294936246,25496894.600770243 6673110.215759593,25496894.60077025 6673110.2157596005,25496871.453753594 6673108.715739627,25496869.323092405 6673148.11807978)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Rautatientori%') and fixed_location.section = 'A';
select check_allu_name('Rautatientori%','D');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496914.291098855 6673188.424581739,25496916.293573853 6673150.613622032,25496892.34366284 6673149.294936246,25496890.445412267 6673187.127858028,25496914.291098855 6673188.424581739)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Rautatientori%') and fixed_location.section = 'D';
select check_allu_name('Rautatientori%','E');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496876.397271853 6673211.058372941,25496877.47872566 6673189.550037191,25496867.19341814 6673188.955368985,25496866.00567316 6673210.558879338,25496876.397271853 6673211.058372941)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Rautatientori%') and fixed_location.section = 'E';
select check_allu_name('Rautatientori%','B');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496916.293573853 6673150.613622036,25496918.06411827 6673114.657034252,25496916.99886356 6673112.012969332,25496894.60077025 6673110.2157596005,25496892.34366284 6673149.294936246,25496916.293573853 6673150.613622036)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Rautatientori%') and fixed_location.section = 'B';
select check_allu_name('Rautatientori%','C');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496890.445412267 6673187.127858028,25496892.34366284 6673149.294936246,25496891.386654407 6673149.24224649,25496891.386654206 6673149.242246335,25496869.323092405 6673148.11807978,25496867.297916148 6673185.927280718,25496890.445412267 6673187.127858028)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Rautatientori%') and fixed_location.section = 'C';
select check_allu_name('Rautatientori%','F');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496896.12639393 6673212.045112652,25496912.93424006 6673212.827576915,25496914.047865696 6673191.5605314085,25496897.407650612 6673190.635583466,25496896.12639393 6673212.045112652)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Rautatientori%') and fixed_location.section = 'F';
DROP FUNCTION check_allu_name(TEXT, TEXT);
