create table allu.codeset (
  id serial primary key,
  type text not null,
  code text not null,
  description text,
  value text,
  unique (type, code));

insert into allu.codeset (type,code,description) values ('Country','AD','Andorra');
insert into allu.codeset (type,code,description) values ('Country','AE','Arabiemiirikunnat');
insert into allu.codeset (type,code,description) values ('Country','AF','Afganistan');
insert into allu.codeset (type,code,description) values ('Country','AG','Antigua ja Barbuda');
insert into allu.codeset (type,code,description) values ('Country','AI','Anguilla');
insert into allu.codeset (type,code,description) values ('Country','AL','Albania');
insert into allu.codeset (type,code,description) values ('Country','AM','Armenia');
insert into allu.codeset (type,code,description) values ('Country','AN','Alankomaiden Antillit');
insert into allu.codeset (type,code,description) values ('Country','AO','Angola');
insert into allu.codeset (type,code,description) values ('Country','AQ','Antarktis');
insert into allu.codeset (type,code,description) values ('Country','AR','Argentiina');
insert into allu.codeset (type,code,description) values ('Country','AS','Amerikan Samoa');
insert into allu.codeset (type,code,description) values ('Country','AT','Itävalta');
insert into allu.codeset (type,code,description) values ('Country','AU','Australia');
insert into allu.codeset (type,code,description) values ('Country','AW','Aruba');
insert into allu.codeset (type,code,description) values ('Country','AX','Ahvenanmaa');
insert into allu.codeset (type,code,description) values ('Country','AZ','Azerbaidzan');
insert into allu.codeset (type,code,description) values ('Country','BA','Bosnia ja Hertsegovina');
insert into allu.codeset (type,code,description) values ('Country','BB','Barbados');
insert into allu.codeset (type,code,description) values ('Country','BD','Bangladesh');
insert into allu.codeset (type,code,description) values ('Country','BE','Belgia');
insert into allu.codeset (type,code,description) values ('Country','BF','Burkina Faso');
insert into allu.codeset (type,code,description) values ('Country','BG','Bulgaria');
insert into allu.codeset (type,code,description) values ('Country','BH','Bahrain');
insert into allu.codeset (type,code,description) values ('Country','BI','Burundi');
insert into allu.codeset (type,code,description) values ('Country','BJ','Benin');
insert into allu.codeset (type,code,description) values ('Country','BM','Bermuda');
insert into allu.codeset (type,code,description) values ('Country','BN','Brunei');
insert into allu.codeset (type,code,description) values ('Country','BO','Bolivia');
insert into allu.codeset (type,code,description) values ('Country','BR','Brasilia');
insert into allu.codeset (type,code,description) values ('Country','BS','Bahama');
insert into allu.codeset (type,code,description) values ('Country','BT','Bhutan');
insert into allu.codeset (type,code,description) values ('Country','BV','Bouvet''nsaari');
insert into allu.codeset (type,code,description) values ('Country','BW','Botswana');
insert into allu.codeset (type,code,description) values ('Country','BY','Valko-Venäjä');
insert into allu.codeset (type,code,description) values ('Country','BZ','Belize');
insert into allu.codeset (type,code,description) values ('Country','CA','Kanada');
insert into allu.codeset (type,code,description) values ('Country','CC','Kookossaaret');
insert into allu.codeset (type,code,description) values ('Country','CD','Kongon demokraattinen tasavalta');
insert into allu.codeset (type,code,description) values ('Country','CF','Keski-Afrikan tasavalta');
insert into allu.codeset (type,code,description) values ('Country','CG','Kongon tasavalta');
insert into allu.codeset (type,code,description) values ('Country','CH','Sveitsi');
insert into allu.codeset (type,code,description) values ('Country','CI','Norsunluurannikko');
insert into allu.codeset (type,code,description) values ('Country','CK','Cookinsaaret');
insert into allu.codeset (type,code,description) values ('Country','CL','Chile');
insert into allu.codeset (type,code,description) values ('Country','CM','Kamerun');
insert into allu.codeset (type,code,description) values ('Country','CN','Kiina');
insert into allu.codeset (type,code,description) values ('Country','CO','Kolumbia');
insert into allu.codeset (type,code,description) values ('Country','CR','Costa Rica');
insert into allu.codeset (type,code,description) values ('Country','CU','Kuuba');
insert into allu.codeset (type,code,description) values ('Country','CV','Kap Verde');
insert into allu.codeset (type,code,description) values ('Country','CX','Joulusaari');
insert into allu.codeset (type,code,description) values ('Country','CY','Kypros');
insert into allu.codeset (type,code,description) values ('Country','CZ','Tsekki');
insert into allu.codeset (type,code,description) values ('Country','DE','Saksa');
insert into allu.codeset (type,code,description) values ('Country','DJ','Djibouti');
insert into allu.codeset (type,code,description) values ('Country','DK','Tanska');
insert into allu.codeset (type,code,description) values ('Country','DM','Dominica');
insert into allu.codeset (type,code,description) values ('Country','DO','Dominikaaninen tasavalta');
insert into allu.codeset (type,code,description) values ('Country','DZ','Algeria');
insert into allu.codeset (type,code,description) values ('Country','EC','Ecuador');
insert into allu.codeset (type,code,description) values ('Country','EE','Viro');
insert into allu.codeset (type,code,description) values ('Country','EG','Egypti');
insert into allu.codeset (type,code,description) values ('Country','EH','Länsi-Sahara');
insert into allu.codeset (type,code,description) values ('Country','ER','Eritrea');
insert into allu.codeset (type,code,description) values ('Country','ES','Espanja');
insert into allu.codeset (type,code,description) values ('Country','ET','Etiopia');
insert into allu.codeset (type,code,description) values ('Country','FI','Suomi');
insert into allu.codeset (type,code,description) values ('Country','FJ','Fidzi');
insert into allu.codeset (type,code,description) values ('Country','FK','Falklandinsaaret');
insert into allu.codeset (type,code,description) values ('Country','FM','Mikronesia');
insert into allu.codeset (type,code,description) values ('Country','FO','Färsaaret');
insert into allu.codeset (type,code,description) values ('Country','FR','Ranska');
insert into allu.codeset (type,code,description) values ('Country','GA','Gabon');
insert into allu.codeset (type,code,description) values ('Country','GB','Yhdistynyt kuningaskunta');
insert into allu.codeset (type,code,description) values ('Country','GD','Grenada');
insert into allu.codeset (type,code,description) values ('Country','GE','Georgia');
insert into allu.codeset (type,code,description) values ('Country','GF','Ranskan Guayana');
insert into allu.codeset (type,code,description) values ('Country','GG','Guernsey');
insert into allu.codeset (type,code,description) values ('Country','GH','Ghana');
insert into allu.codeset (type,code,description) values ('Country','GI','Gibraltar');
insert into allu.codeset (type,code,description) values ('Country','GL','Grönlanti');
insert into allu.codeset (type,code,description) values ('Country','GM','Gambia');
insert into allu.codeset (type,code,description) values ('Country','GN','Guinea');
insert into allu.codeset (type,code,description) values ('Country','GP','Guadeloupe');
insert into allu.codeset (type,code,description) values ('Country','GQ','Päiväntasaajan Guinea');
insert into allu.codeset (type,code,description) values ('Country','GR','Kreikka');
insert into allu.codeset (type,code,description) values ('Country','GS','Etelä-Georgia ja Eteläiset Sandwichsaaret');
insert into allu.codeset (type,code,description) values ('Country','GT','Guatemala');
insert into allu.codeset (type,code,description) values ('Country','GU','Guam');
insert into allu.codeset (type,code,description) values ('Country','GW','Guinea-Bissau');
insert into allu.codeset (type,code,description) values ('Country','GY','Guyana');
insert into allu.codeset (type,code,description) values ('Country','HK','Hongkong');
insert into allu.codeset (type,code,description) values ('Country','HM','Heard ja McDonaldinsaaret');
insert into allu.codeset (type,code,description) values ('Country','HN','Honduras');
insert into allu.codeset (type,code,description) values ('Country','HR','Kroatia');
insert into allu.codeset (type,code,description) values ('Country','HT','Haiti');
insert into allu.codeset (type,code,description) values ('Country','HU','Unkari');
insert into allu.codeset (type,code,description) values ('Country','ID','Indonesia');
insert into allu.codeset (type,code,description) values ('Country','IE','Irlanti');
insert into allu.codeset (type,code,description) values ('Country','IL','Israel');
insert into allu.codeset (type,code,description) values ('Country','IM','Mansaari');
insert into allu.codeset (type,code,description) values ('Country','IN','Intia');
insert into allu.codeset (type,code,description) values ('Country','IO','Brittiläinen Intian valtameren alue');
insert into allu.codeset (type,code,description) values ('Country','IQ','Irak');
insert into allu.codeset (type,code,description) values ('Country','IR','Iran');
insert into allu.codeset (type,code,description) values ('Country','IS','Islanti');
insert into allu.codeset (type,code,description) values ('Country','IT','Italia');
insert into allu.codeset (type,code,description) values ('Country','JE','Jersey');
insert into allu.codeset (type,code,description) values ('Country','JM','Jamaika');
insert into allu.codeset (type,code,description) values ('Country','JO','Jordania');
insert into allu.codeset (type,code,description) values ('Country','JP','Japani');
insert into allu.codeset (type,code,description) values ('Country','KE','Kenia');
insert into allu.codeset (type,code,description) values ('Country','KG','Kirgisia');
insert into allu.codeset (type,code,description) values ('Country','KH','Kambodza');
insert into allu.codeset (type,code,description) values ('Country','KI','Kiribati');
insert into allu.codeset (type,code,description) values ('Country','KM','Komorit');
insert into allu.codeset (type,code,description) values ('Country','KN','Saint Kitts ja Nevis');
insert into allu.codeset (type,code,description) values ('Country','KP','Korean demokraattinen kansantasavalta');
insert into allu.codeset (type,code,description) values ('Country','KR','Korean tasavalta');
insert into allu.codeset (type,code,description) values ('Country','KW','Kuwait');
insert into allu.codeset (type,code,description) values ('Country','KY','Caymansaaret');
insert into allu.codeset (type,code,description) values ('Country','KZ','Kazakstan');
insert into allu.codeset (type,code,description) values ('Country','LA','Laos');
insert into allu.codeset (type,code,description) values ('Country','LB','Libanon');
insert into allu.codeset (type,code,description) values ('Country','LC','Saint Lucia');
insert into allu.codeset (type,code,description) values ('Country','LI','Liechtenstein');
insert into allu.codeset (type,code,description) values ('Country','LK','Sri Lanka');
insert into allu.codeset (type,code,description) values ('Country','LR','Liberia');
insert into allu.codeset (type,code,description) values ('Country','LS','Lesotho');
insert into allu.codeset (type,code,description) values ('Country','LT','Liettua');
insert into allu.codeset (type,code,description) values ('Country','LU','Luxemburg');
insert into allu.codeset (type,code,description) values ('Country','LV','Latvia');
insert into allu.codeset (type,code,description) values ('Country','LY','Libya');
insert into allu.codeset (type,code,description) values ('Country','MA','Marokko');
insert into allu.codeset (type,code,description) values ('Country','MC','Monaco');
insert into allu.codeset (type,code,description) values ('Country','MD','Moldova');
insert into allu.codeset (type,code,description) values ('Country','ME','Montenegro');
insert into allu.codeset (type,code,description) values ('Country','MG','Madagaskar');
insert into allu.codeset (type,code,description) values ('Country','MH','Marshallinsaaret');
insert into allu.codeset (type,code,description) values ('Country','MK','Makedonia');
insert into allu.codeset (type,code,description) values ('Country','ML','Mali');
insert into allu.codeset (type,code,description) values ('Country','MM','Myanmar');
insert into allu.codeset (type,code,description) values ('Country','MN','Mongolia');
insert into allu.codeset (type,code,description) values ('Country','MO','Macao');
insert into allu.codeset (type,code,description) values ('Country','MP','Pohjois-Mariaanit');
insert into allu.codeset (type,code,description) values ('Country','MQ','Martinique');
insert into allu.codeset (type,code,description) values ('Country','MR','Mauritania');
insert into allu.codeset (type,code,description) values ('Country','MS','Montserrat');
insert into allu.codeset (type,code,description) values ('Country','MT','Malta');
insert into allu.codeset (type,code,description) values ('Country','MU','Mauritius');
insert into allu.codeset (type,code,description) values ('Country','MV','Malediivit');
insert into allu.codeset (type,code,description) values ('Country','MW','Malawi');
insert into allu.codeset (type,code,description) values ('Country','MX','Meksiko');
insert into allu.codeset (type,code,description) values ('Country','MY','Malesia');
insert into allu.codeset (type,code,description) values ('Country','MZ','Mosambik');
insert into allu.codeset (type,code,description) values ('Country','NA','Namibia');
insert into allu.codeset (type,code,description) values ('Country','NC','Uusi-Kaledonia');
insert into allu.codeset (type,code,description) values ('Country','NE','Niger');
insert into allu.codeset (type,code,description) values ('Country','NF','Norfolkinsaari');
insert into allu.codeset (type,code,description) values ('Country','NG','Nigeria');
insert into allu.codeset (type,code,description) values ('Country','NI','Nicaragua');
insert into allu.codeset (type,code,description) values ('Country','NL','Alankomaat');
insert into allu.codeset (type,code,description) values ('Country','NO','Norja');
insert into allu.codeset (type,code,description) values ('Country','NP','Nepal');
insert into allu.codeset (type,code,description) values ('Country','NR','Nauru');
insert into allu.codeset (type,code,description) values ('Country','NU','Niue');
insert into allu.codeset (type,code,description) values ('Country','NZ','Uusi-Seelanti');
insert into allu.codeset (type,code,description) values ('Country','OM','Oman');
insert into allu.codeset (type,code,description) values ('Country','PA','Panama');
insert into allu.codeset (type,code,description) values ('Country','PE','Peru');
insert into allu.codeset (type,code,description) values ('Country','PF','Ranskan Polynesia');
insert into allu.codeset (type,code,description) values ('Country','PG','Papua-Uusi-Guinea');
insert into allu.codeset (type,code,description) values ('Country','PH','Filippiinit');
insert into allu.codeset (type,code,description) values ('Country','PK','Pakistan');
insert into allu.codeset (type,code,description) values ('Country','PL','Puola');
insert into allu.codeset (type,code,description) values ('Country','PM','Saint-Pierre ja Miquelon');
insert into allu.codeset (type,code,description) values ('Country','PN','Pitcairn');
insert into allu.codeset (type,code,description) values ('Country','PR','Puerto Rico');
insert into allu.codeset (type,code,description) values ('Country','PS','Palestiina');
insert into allu.codeset (type,code,description) values ('Country','PT','Portugali');
insert into allu.codeset (type,code,description) values ('Country','PW','Palau');
insert into allu.codeset (type,code,description) values ('Country','PY','Paraguay');
insert into allu.codeset (type,code,description) values ('Country','QA','Qatar');
insert into allu.codeset (type,code,description) values ('Country','RE','Réunion');
insert into allu.codeset (type,code,description) values ('Country','RO','Romania');
insert into allu.codeset (type,code,description) values ('Country','RS','Serbia');
insert into allu.codeset (type,code,description) values ('Country','RU','Venäjä');
insert into allu.codeset (type,code,description) values ('Country','RW','Ruanda');
insert into allu.codeset (type,code,description) values ('Country','SA','Saudi-Arabia');
insert into allu.codeset (type,code,description) values ('Country','SB','Salomonsaaret');
insert into allu.codeset (type,code,description) values ('Country','SC','Seychellit');
insert into allu.codeset (type,code,description) values ('Country','SD','Sudan');
insert into allu.codeset (type,code,description) values ('Country','SE','Ruotsi');
insert into allu.codeset (type,code,description) values ('Country','SG','Singapore');
insert into allu.codeset (type,code,description) values ('Country','SH','Saint Helena');
insert into allu.codeset (type,code,description) values ('Country','SI','Slovenia');
insert into allu.codeset (type,code,description) values ('Country','SJ','Svalbard ja Jan Mayen');
insert into allu.codeset (type,code,description) values ('Country','SK','Slovakia');
insert into allu.codeset (type,code,description) values ('Country','SL','Sierra Leone');
insert into allu.codeset (type,code,description) values ('Country','SM','San Marino');
insert into allu.codeset (type,code,description) values ('Country','SN','Senegal');
insert into allu.codeset (type,code,description) values ('Country','SO','Somalia');
insert into allu.codeset (type,code,description) values ('Country','SR','Suriname');
insert into allu.codeset (type,code,description) values ('Country','SS','Etelä-Sudan');
insert into allu.codeset (type,code,description) values ('Country','ST','São Tomé ja Príncipe');
insert into allu.codeset (type,code,description) values ('Country','SV','El Salvador');
insert into allu.codeset (type,code,description) values ('Country','SY','Syyria');
insert into allu.codeset (type,code,description) values ('Country','SZ','Swazimaa');
insert into allu.codeset (type,code,description) values ('Country','TC','Turks- ja Caicossaaret');
insert into allu.codeset (type,code,description) values ('Country','TD','Tsad');
insert into allu.codeset (type,code,description) values ('Country','TF','Ranskan eteläiset alueet');
insert into allu.codeset (type,code,description) values ('Country','TG','Togo');
insert into allu.codeset (type,code,description) values ('Country','TH','Thaimaa');
insert into allu.codeset (type,code,description) values ('Country','TJ','Tadzikistan');
insert into allu.codeset (type,code,description) values ('Country','TK','Tokelau');
insert into allu.codeset (type,code,description) values ('Country','TL','Itä-Timor');
insert into allu.codeset (type,code,description) values ('Country','TM','Turkmenistan');
insert into allu.codeset (type,code,description) values ('Country','TN','Tunisia');
insert into allu.codeset (type,code,description) values ('Country','TO','Tonga');
insert into allu.codeset (type,code,description) values ('Country','TR','Turkki');
insert into allu.codeset (type,code,description) values ('Country','TT','Trinidad ja Tobago');
insert into allu.codeset (type,code,description) values ('Country','TV','Tuvalu');
insert into allu.codeset (type,code,description) values ('Country','TW','Taiwan');
insert into allu.codeset (type,code,description) values ('Country','TZ','Tansania');
insert into allu.codeset (type,code,description) values ('Country','UA','Ukraina');
insert into allu.codeset (type,code,description) values ('Country','UG','Uganda');
insert into allu.codeset (type,code,description) values ('Country','UM','Yhdysvaltain pienet erillissaaret');
insert into allu.codeset (type,code,description) values ('Country','US','Yhdysvallat');
insert into allu.codeset (type,code,description) values ('Country','UY','Uruguay');
insert into allu.codeset (type,code,description) values ('Country','UZ','Uzbekistan');
insert into allu.codeset (type,code,description) values ('Country','VA','Vatikaani');
insert into allu.codeset (type,code,description) values ('Country','VC','Saint Vincent ja Grenadiinit');
insert into allu.codeset (type,code,description) values ('Country','VE','Venezuela');
insert into allu.codeset (type,code,description) values ('Country','WF','Wallis ja Futuna');
insert into allu.codeset (type,code,description) values ('Country','VG','Brittiläiset Neitsytsaaret');
insert into allu.codeset (type,code,description) values ('Country','VI','Yhdysvaltain Neitsytsaaret');
insert into allu.codeset (type,code,description) values ('Country','VN','Vietnam');
insert into allu.codeset (type,code,description) values ('Country','WS','Samoa');
insert into allu.codeset (type,code,description) values ('Country','VU','Vanuatu');
insert into allu.codeset (type,code,description) values ('Country','XK','Kosovo');
insert into allu.codeset (type,code,description) values ('Country','YE','Jemen');
insert into allu.codeset (type,code,description) values ('Country','YT','Mayotte');
insert into allu.codeset (type,code,description) values ('Country','ZA','Etelä-Afrikka');
insert into allu.codeset (type,code,description) values ('Country','ZM','Sambia');
insert into allu.codeset (type,code,description) values ('Country','ZW','Zimbabwe');

alter table allu.customer add column country_id integer references allu.codeset(id);
update allu.customer set country_id=(select id from allu.codeset where type='Country' and code='FI');
alter table allu.customer alter column country_id set not null;

insert into attribute_meta (structure_meta_id,name,ui_name,data_type) values
  ((select id from structure_meta where type_name='Customer'),'country','Maan tunniste','INTEGER');