-- DO NOT EDIT THIS FILE MANUALLY!

-- This file was autogenerated. The command used was:
-- java -Dloader.main=fi.hel.allu.model.deployment.LocationGeometryReader -classpath target/model-service-1.0-SNAPSHOT.jar org.springframework.boot.loader.PropertiesLauncher /home/mikko/prj/allu/sesonki_keskuskatu_siirto.geojson output.sql

-- See the documentation for more info.

CREATE FUNCTION check_allu_name(areaname TEXT, sectionname TEXT)
RETURNS VOID AS $$
DECLARE
   match_count INT;
BEGIN
   IF sectionname IS NULL OR sectionname = '' THEN
       SELECT COUNT(*) INTO STRICT match_count FROM
           (SELECT DISTINCT a.name as areaname, fl.section as section FROM
            allu.fixed_location as fl inner join allu.location_area as a on fl.area_id=a.id) as l WHERE
           l.areaname LIKE check_allu_name.areaname AND l.section IS NULL;
   ELSE
       SELECT COUNT(*) INTO STRICT match_count FROM
           (SELECT DISTINCT a.name as areaname, fl.section as section FROM
            allu.fixed_location as fl inner join allu.location_area as a on fl.area_id=a.id) as l WHERE
           l.areaname LIKE check_allu_name.areaname AND l.section = sectionname;
   END IF;
   IF match_count <> 1 THEN
       RAISE EXCEPTION 'Name % matches % areas in database', check_allu_name.areaname, match_count;
   END IF;
END;
$$ LANGUAGE plpgsql;
-- input file: /home/mikko/prj/allu/sesonki_keskuskatu_siirto.geojson
select check_allu_name('Keskuskatu%','F');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(MULTIPOLYGON(((25496831.004699808 6672956.667324745,25496827.84601972 6672956.4744915385,25496827.67616537 6672959.64024467,25496830.82771342 6672959.826122404,25496831.004699808 6672956.667324745))))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Keskuskatu%') and fixed_location.section = 'F';
select check_allu_name('Keskuskatu%','A');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(MULTIPOLYGON(((25496827.501392156 6672962.806292906,25496824.342717163 6672962.613462715,25496824.172866136 6672965.779216039,25496827.32440909 6672965.965090762,25496827.501392156 6672962.806292906))))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Keskuskatu%') and fixed_location.section = 'A';
select check_allu_name('Keskuskatu%','D');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(MULTIPOLYGON(((25496830.82964641 6672959.833553089,25496827.670969035 6672959.640720028,25496827.501114987 6672962.806473184,25496830.652660325 6672962.992350769,25496830.82964641 6672959.833553089))))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Keskuskatu%') and fixed_location.section = 'D';
select check_allu_name('Keskuskatu%','E');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(MULTIPOLYGON(((25496827.849464413 6672956.483386054,25496824.690783996 6672956.290555562,25496824.52093236 6672959.456308843,25496827.672480732 6672959.642183865,25496827.849464413 6672956.483386054))))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Keskuskatu%') and fixed_location.section = 'E';
select check_allu_name('Keskuskatu%','B');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(MULTIPOLYGON(((25496830.660042997 6672963.001912428,25496827.501368344 6672962.809079517,25496827.331514597 6672965.974832693,25496830.48305722 6672966.160710134,25496830.660042997 6672963.001912428))))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Keskuskatu%') and fixed_location.section = 'B';
select check_allu_name('Keskuskatu%','C');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(MULTIPOLYGON(((25496827.67665952 6672959.645467451,25496824.51798182 6672959.452637108,25496824.348130483 6672962.618390409,25496827.499676146 6672962.804265286,25496827.67665952 6672959.645467451))))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Keskuskatu%') and fixed_location.section = 'C';
DROP FUNCTION check_allu_name(TEXT, TEXT);
