-- DO NOT EDIT THIS FILE MANUALLY!

-- This file was autogenerated. The command used was:
-- java -Dloader.main=fi.hel.allu.model.deployment.LocationGeometryReader -classpath backend/model-service/target/model-service-1.0-SNAPSHOT.jar org.springframework.boot.loader.PropertiesLauncher kolmensepan_joulusesonki.geojson eitoimi.sql

-- See the documentation for more info.

insert into fixed_location (area_id,section,application_kind,is_active) values ((select id from location_area where name = 'Kolmensepänaukio'),'J1','SEASON_SALE',true);
insert into fixed_location (area_id,section,application_kind,is_active) values ((select id from location_area where name = 'Kolmensepänaukio'),'J2','SEASON_SALE',true);
insert into fixed_location (area_id,section,application_kind,is_active) values ((select id from location_area where name = 'Kolmensepänaukio'),'J3','SEASON_SALE',true);
insert into fixed_location (area_id,section,application_kind,is_active) values ((select id from location_area where name = 'Kolmensepänaukio'),'J4','SEASON_SALE',true);
insert into fixed_location (area_id,section,application_kind,is_active) values ((select id from location_area where name = 'Kolmensepänaukio'),'J5','SEASON_SALE',true);
insert into fixed_location (area_id,section,application_kind,is_active) values ((select id from location_area where name = 'Kolmensepänaukio'),'J6','SEASON_SALE',true);
insert into fixed_location (area_id,section,application_kind,is_active) values ((select id from location_area where name = 'Kolmensepänaukio'),'J7','SEASON_SALE',true);
insert into fixed_location (area_id,section,application_kind,is_active) values ((select id from location_area where name = 'Kolmensepänaukio'),'J8','SEASON_SALE',true);
insert into fixed_location (area_id,section,application_kind,is_active) values ((select id from location_area where name = 'Kolmensepänaukio'),'J9','SEASON_SALE',true);
insert into fixed_location (area_id,section,application_kind,is_active) values ((select id from location_area where name = 'Kolmensepänaukio'),'J10','SEASON_SALE',true);
insert into fixed_location (area_id,section,application_kind,is_active) values ((select id from location_area where name = 'Kolmensepänaukio'),'J11','SEASON_SALE',true);
insert into fixed_location (area_id,section,application_kind,is_active) values ((select id from location_area where name = 'Kolmensepänaukio'),'J12','SEASON_SALE',true);

CREATE FUNCTION check_allu_name(areaname TEXT, sectionname TEXT)
RETURNS VOID AS $$
DECLARE
   match_count INT;
BEGIN
   IF sectionname IS NULL OR sectionname = '' THEN
       SELECT COUNT(*) INTO STRICT match_count FROM
           (SELECT DISTINCT a.name as areaname, fl.section as section FROM
            allu.fixed_location as fl inner join allu.location_area as a on fl.area_id=a.id) as l WHERE
           l.areaname LIKE check_allu_name.areaname AND l.section IS NULL;
   ELSE
       SELECT COUNT(*) INTO STRICT match_count FROM
           (SELECT DISTINCT a.name as areaname, fl.section as section FROM
            allu.fixed_location as fl inner join allu.location_area as a on fl.area_id=a.id) as l WHERE
           l.areaname LIKE check_allu_name.areaname AND l.section = sectionname;
   END IF;
   IF match_count <> 1 THEN
       RAISE EXCEPTION 'Name % matches % areas in database', check_allu_name.areaname, match_count;
   END IF;
END;
$$ LANGUAGE plpgsql;
-- input file: kolmensepan_joulusesonki.geojson
select check_allu_name('Kolmensepänaukio%','J9');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496720.422379464 6672871.903200339,25496720.59515274 6672875.058473605,25496723.750426017 6672874.885700337,25496723.57765273 6672871.730427063,25496720.422379464 6672871.903200339)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Kolmensepänaukio%') and fixed_location.section = 'J9';
select check_allu_name('Kolmensepänaukio%','J8');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496723.624277666 6672871.7017057305,25496724.92134297 6672874.583236852,25496727.802874092 6672873.286171553,25496726.50580878 6672870.404640431,25496723.624277666 6672871.7017057305)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Kolmensepänaukio%') and fixed_location.section = 'J8';
select check_allu_name('Kolmensepänaukio%','J3');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496738.470791798 6672875.325840434,25496741.043331765 6672877.160952996,25496742.878444333 6672874.588413037,25496740.30590437 6672872.75330047,25496738.470791798 6672875.325840434)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Kolmensepänaukio%') and fixed_location.section = 'J3';
select check_allu_name('Kolmensepänaukio%','J2');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496741.469402913 6672877.464555715,25496744.04194288 6672879.299668278,25496745.877055448 6672876.7271283185,25496743.304515485 6672874.892015751,25496741.469402913 6672877.464555715)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Kolmensepänaukio%') and fixed_location.section = 'J2';
select check_allu_name('Kolmensepänaukio%','J11');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496710.47802722 6672874.974916865,25496713.003918737 6672876.873724929,25496714.902726803 6672874.347833416,25496712.376835287 6672872.4490253525,25496710.47802722 6672874.974916865)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Kolmensepänaukio%') and fixed_location.section = 'J11';
select check_allu_name('Kolmensepänaukio%','J5');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496732.80429278 6672871.202714542,25496735.376803093 6672873.037868672,25496737.211957227 6672870.465358366,25496734.639446914 6672868.630204231,25496732.80429278 6672871.202714542)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Kolmensepänaukio%') and fixed_location.section = 'J5';
select check_allu_name('Kolmensepänaukio%','J12');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496708.503717892 6672877.613333392,25496711.02960941 6672879.512141456,25496712.928417474 6672876.986249943,25496710.402525958 6672875.087441879,25496708.503717892 6672877.613333392)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Kolmensepänaukio%') and fixed_location.section = 'J12';
select check_allu_name('Kolmensepänaukio%','J4');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496735.62652096 6672873.275319599,25496738.199060928 6672875.110432161,25496740.034173496 6672872.537892202,25496737.461633533 6672870.702779635,25496735.62652096 6672873.275319599)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Kolmensepänaukio%') and fixed_location.section = 'J4';
select check_allu_name('Kolmensepänaukio%','J10');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496712.4467361 6672872.342100788,25496714.972627617 6672874.240908852,25496716.871435683 6672871.715017339,25496714.345544167 6672869.816209275,25496712.4467361 6672872.342100788)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Kolmensepänaukio%') and fixed_location.section = 'J10';
select check_allu_name('Kolmensepänaukio%','J1');
update allu.fixed_location
set geometry = 'SRID=3879;GEOMETRYCOLLECTION(POLYGON((25496744.445965417 6672879.515076551,25496747.018505383 6672881.350189113,25496748.85361795 6672878.777649154,25496746.28107799 6672876.942536587,25496744.445965417 6672879.515076551)))'
where fixed_location.area_id = (select location_area.id
from allu.location_area location_area
where location_area.name like 'Kolmensepänaukio%') and fixed_location.section = 'J1';
DROP FUNCTION check_allu_name(TEXT, TEXT);
