export enum InformationRequestFieldKey {
  CUSTOMER = 'CUSTOMER',
  INVOICING_CUSTOMER = 'INVOICING_CUSTOMER',
  PROPERTY_DEVELOPER = 'PROPERTY_DEVELOPER',
  CONTRACTOR = 'CONTRACTOR',
  REPRESENTATIVE = 'REPRESENTATIVE',
  GEOMETRY = 'GEOMETRY',
  START_TIME = 'START_TIME',
  END_TIME = 'END_TIME',
  IDENTIFICATION_NUMBER = 'IDENTIFICATION_NUMBER',
  CLIENT_APPLICATION_KIND = 'CLIENT_APPLICATION_KIND',
  APPLICATION_KIND = 'APPLICATION_KIND',
  POSTAL_ADDRESS = 'POSTAL_ADDRESS',
  WORK_DESCRIPTION = 'WORK_DESCRIPTION',
  PROPERTY_IDENTIFICATION_NUMBER = 'PROPERTY_IDENTIFICATION_NUMBER',
  ATTACHMENT = 'ATTACHMENT',
  AREA = 'AREA'
}

export const LocationKeys: InformationRequestFieldKey[] = [
  InformationRequestFieldKey.GEOMETRY,
  InformationRequestFieldKey.POSTAL_ADDRESS,
  InformationRequestFieldKey.AREA
];

export const OtherInfoKeys: InformationRequestFieldKey[] = [
  InformationRequestFieldKey.START_TIME,
  InformationRequestFieldKey.END_TIME,
  InformationRequestFieldKey.IDENTIFICATION_NUMBER,
  InformationRequestFieldKey.WORK_DESCRIPTION,
  InformationRequestFieldKey.PROPERTY_IDENTIFICATION_NUMBER
];
