export enum InformationRequestFieldKey {
  CUSTOMER,
  INVOICING_CUSTOMER,
  GEOMETRY,
  START_TIME,
  END_TIME,
  IDENTIFICATION_NUMBER,
  CLIENT_APPLICATION_KIND,
  APPLICATION_KIND,
  POSTAL_ADDRESS,
  WORK_DESCRIPTION,
  PROPERTY_IDENTIFICATION_NUMBER,
  ATTACHMENT
}
