- include_tasks: firewall.yml
- include_tasks: usersetup.yml
- include_tasks: postgresql.yml
- include_tasks: create_directories.yml
- include_tasks: docker.yml branch="{{ branch }}"
- include_tasks: database.yml
