export enum PruneDataTab {
  AREA_RENTALS = 'AREA_RENTALS',
  CABLE_REPORTS = 'CABLE_REPORTS',
  EXCAVATION_ANNOUNCEMENTS = 'EXCAVATION_ANNOUNCEMENTS',
  SHORT_TERM_RENTALS = 'SHORT_TERM_RENTALS',
  PLACEMENT_CONTRACTS = 'PLACEMENT_CONTRACTS',
  EVENTS = 'EVENTS',
  TRAFFIC_ARRANGEMENTS = 'TRAFFIC_ARRANGEMENTS',
  USER_DATA = 'USER_DATA'
}

export const pruneDataTabs = [
  PruneDataTab.AREA_RENTALS,
  PruneDataTab.CABLE_REPORTS,
  PruneDataTab.EXCAVATION_ANNOUNCEMENTS,
  PruneDataTab.SHORT_TERM_RENTALS,
  PruneDataTab.PLACEMENT_CONTRACTS,
  PruneDataTab.EVENTS,
  PruneDataTab.TRAFFIC_ARRANGEMENTS,
  PruneDataTab.USER_DATA
]; 