export enum PruneDataTab {
  AREA_RENTALS = 'AREA_RENTAL',
  CABLE_REPORTS = 'CABLE_REPORT',
  EXCAVATION_ANNOUNCEMENTS = 'EXCAVATION_ANNOUNCEMENT',
  SHORT_TERM_RENTALS = 'SHORT_TERM_RENTAL',
  PLACEMENT_CONTRACTS = 'PLACEMENT_CONTRACT',
  EVENTS = 'EVENT',
  TRAFFIC_ARRANGEMENTS = 'TEMPORARY_TRAFFIC_ARRANGEMENTS',
  USER_DATA = 'USER_DATA'
}

export const pruneDataTabs = [
  PruneDataTab.AREA_RENTALS,
  PruneDataTab.CABLE_REPORTS,
  PruneDataTab.EXCAVATION_ANNOUNCEMENTS,
  PruneDataTab.SHORT_TERM_RENTALS,
  PruneDataTab.PLACEMENT_CONTRACTS,
  PruneDataTab.EVENTS,
  PruneDataTab.TRAFFIC_ARRANGEMENTS,
  PruneDataTab.USER_DATA
]; 