export enum ConfigurationKey {
  CUSTOMER_NOTIFICATION_RECEIVER_EMAIL = 'CUSTOMER_NOTIFICATION_RECEIVER_EMAIL',
  INVOICE_NOTIFICATION_RECEIVER_EMAIL = 'INVOICE_NOTIFICATION_RECEIVER_EMAIL',
  PLACEMENT_CONTRACT_DECISION_MAKER = 'PLACEMENT_CONTRACT_DECISION_MAKER',
  WINTER_TIME_START = 'WINTER_TIME_START',
  WINTER_TIME_END = 'WINTER_TIME_END',
  PLACEMENT_CONTRACT_SECTION_NUMBER_YEAR = 'PLACEMENT_CONTRACT_SECTION_NUMBER_YEAR'
}
