- name: create apache directory under allu home
  file: path=/home/allu/apache
        state=directory
        owner=allu
        group=allu
        mode="u=rwx,g=rx,o=rx"

- name: create apache sites directory under allu home
  file: path=/home/allu/apache/sites-available
        state=directory
        owner=allu
        group=allu
        mode="u=rwx,g=rx,o=rx"

- name: create apache www directory under allu home
  file: path=/home/allu/apache/www
        state=directory
        owner=allu
        group=allu
        mode="u=rwx,g=rx,o=rx"

- name: create mapproxy directory under allu home
  file: path=/home/allu/mapproxy
        state=directory
        owner=allu
        group=allu
        mode="u=rwx,g=rx,o=rx"

- name: create mapproxy configuration directory
  file: path=/home/allu/mapproxy/configuration
        state=directory
        owner=allu
        group=allu
        mode="u=rwx,g=rx,o=rx"

- name: create mapproxy python directory
  file: path=/home/allu/mapproxy/python
        state=directory
        owner=allu
        group=allu
        mode="u=rwx,g=rx,o=rx"

- name: create mapproxy logging directory
  file: path=/home/allu/mapproxy/logs
        state=directory
        owner=allu
        group=allu
        mode="u=rwx,g=rx,o=rx"

- name: create mapproxy cache directory
  file: path=/home/allu/mapproxy/cache_data
        state=directory
        owner=allu
        group=allu
        mode="u=rwx,g=rx,o=rx"
