- name: Login to GitLab repository locally
  local_action:
    module: docker_login
    registry: "{{ gitlab_registry_url }}"
    username: "{{ gitlab_deploy_user }}"
    password: "{{ gitlab_deploy_token }}"

- name: Build frontend Docker image. Uses random numbers to force Docker to build certain parts of image every time
  local_action:
    module: docker_image
    source: build
    build:
      args:
        CUSTOM_UID: "{{ system_user_id_allu }}"
        CUSTOM_GID: "{{ system_group_id_allu }}"
        CACHEBUST: "{{ 9999999 |random }}"
      path: "{{ role_path }}/files/frontend_docker"
    name: "allu_frontend:{{ branch }}"
    force_source: true

- name: Push built allu_frontend Docker image to GitLab repository
  local_action:
    module: docker_image
    push: true
    source: local
    force_tag: true  # As branch may already be present, we need to enable overwriting of existing tags
    name: "allu_frontend:{{ branch }}"
    repository: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_frontend:{{ branch }}"

- name: Start Docker services on remote host
  service: name=docker state=started
  become: yes

- name: Stop and remove existing allu_frontend container from Docker
  docker_container:
    name: "{{ frontend_name }}"
    state: absent
  become: yes

- name: Remove existing allu_frontend image from Docker
  docker_image:
    name: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_frontend:{{ branch }}"
    state: absent
    force_absent: true
  become: yes
  when: "'test' in group_names or 'staging' in group_names"

- name: Login to GitLab repository at the remote
  docker_login:
    registry: "{{ gitlab_registry_url }}/vincit/allu/allu"
    username: "{{ gitlab_deploy_user }}"
    password: "{{ gitlab_deploy_token }}"
  become: yes

- name: Pull allu_frontend Docker image from GitLab repository
  docker_image:
    source: pull
    name: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_frontend:{{ branch }}"
  become: yes

- name: Start allu_frontend container
  docker_container:
    name: "{{ frontend_name }}"
    image: "{{ gitlab_registry_url }}/vincit/allu/allu/allu_frontend:{{ branch }}"
    restart_policy: always
    volumes:
      - /home/allu/apache/sites-available:/etc/apache2/sites-available:rw
      - /home/allu/apache/www:/var/www/html:rw
      - /srv/data/allu/mapproxy:/mapproxy:rw
      - /home/allu/ssl:/etc/ssl/allu:rw
    published_ports:
      - "80:80"
      - "443:443"
    networks:
      - name: "{{ network_name }}"
        aliases:
          - frontendcontainer
  become: yes
