
- name: Build frontend Docker image. Uses random numbers to force Docker to build certain parts of image every time
  local_action:
    module: docker_image
    path: "{{ role_path }}/files/frontend_docker"
    name: allu_frontend
    force: true
    buildargs:
      CACHEBUST: "{{ 9999999 |random }}"

- name: remove existing docker image to avoid Ansible task caching
  local_action: file path=/tmp/allu_frontend.tar state=absent

# This task requires docker-py to be installed on the local host. Also the user who's executing Ansible has to belong to docker group to be
# able to use docker without super user rights
- name: save local Docker image as file on local host
  local_action: docker_image
                name=allu_frontend
                archive_path=/tmp/allu_frontend.tar
                state=present

- name: gzip Docker image on local host
  local_action: archive
                path=/tmp/allu_frontend.tar
                remove=true

- name: copy Docker image to target host
  copy: src=/tmp/allu_frontend.tar.gz dest=/tmp
            owner=allu
            group=allu
            mode="u=rwx,g=rx,o=rx"

- name: extract tar from Docker gzipped image
  command: gunzip -f /tmp/allu_frontend.tar.gz

- name: stop and remove existing container from Docker
  docker_container:
    name: allu_frontend_container
    state: absent
  become: yes

- name: remove existing container from Docker
  docker_image:
    name=allu_frontend
    state=absent
    force=true
  become: yes

- name: add container to Docker
  docker_image:
    name=allu_frontend
    state=present
    load_path=/tmp/allu_frontend.tar
  become: yes

- name: start container
  docker_container:
    name: allu_frontend_container
    image: allu_frontend
    restart_policy: always
    volumes:
      - /home/allu/apache/sites-available:/etc/apache2/sites-available:rw
      - /home/allu/apache/www:/var/www/html:rw
      - /home/allu/mapproxy:/mapproxy:rw
    published_ports:
      - "80:80"
      - "443:443"
  become: yes
