---
- name: check if zabbix-release is installed
  command: dpkg -s zabbix-release
  register: zabbix_proxy_release_dpkg
  changed_when: false
  failed_when: false

- name: install zabbix-release deb
  apt: deb="https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+{{ ansible_distribution_release }}_all.deb"
  when: zabbix_proxy_release_dpkg.rc != 0

- name: refresh apt
  apt: update_cache=yes
  when: zabbix_proxy_release_dpkg.rc != 0

- name: refresh apt if required
  apt: cache_valid_time=3600 update_cache=yes
  when: zabbix_proxy_release_dpkg.rc != 0

- name: install zabbix-proxy-sqlite3
  apt: name=zabbix-proxy-sqlite3 state=latest install_recommends=no
